/**
 * Promo Campaign Content — July 28, 2026
 *
 * Generated by Agent A9 (Monetization & Growth).
 * Ready-to-use marketing copy for premium upgrades, referral programs,
 * and coin system promotions.
 *
 * Theme: "Generation Launch Week" — Pollinations.ai integration is LIVE!
 * AniVerse is no longer just a gallery — it's now a functional AI anime creator.
 * This campaign capitalizes on the launch momentum to drive upgrades.
 */

export interface PromoCampaign {
  date: string;
  campaignName: string;
  /** Primary CTA for premium upgrade. */
  premiumUpgrade: {
    headline: string;
    subheadline: string;
    body: string;
    cta: string;
    ctaLink: string;
    targetAudience: string;
  };
  /** Referral program copy. */
  referralProgram: {
    headline: string;
    body: string;
    rewardDescription: string;
    cta: string;
    ctaLink: string;
  };
  /** Coin system promotion. */
  coinPromo: {
    headline: string;
    body: string;
    cta: string;
    ctaLink: string;
  };
  /** Social media promo snippets. */
  socialSnippets: {
    twitter: string[];
    instagram: string[];
    discord: string[];
  };
  /** Email marketing copy. */
  emailCampaign: {
    subject: string;
    previewText: string;
    body: string;
  };
}

export const promoCampaign: PromoCampaign = {
  date: "2026-07-28",
  campaignName: "🎨 Generation Launch Week — Your AI Anime Creator is Here!",

  premiumUpgrade: {
    headline: "Generate Anime Art in Your Browser — Instantly ✨",
    subheadline:
      "AniVerse just got superpowers. Generate stunning AI anime art directly from your dashboard — 16 style presets, one click, no setup needed.",
    body:
      "We just launched the feature you've been waiting for: **AI anime generation, live in your browser.** 🚀\\\\n\\\\n" +
      "No external tools, no API keys, no technical setup. Just pick your style, write your prompt, and create.\\\\n\\\\n" +
      "🎨 **How it works:**\\\\n" +
      "1. Choose from 16 curated style presets (Ghibli, Cyberpunk, Retro 90s, etc.)\\\\n" +
      "2. Describe your scene or character\\\\n" +
      "3. Click Generate — your artwork appears instantly\\\\n" +
      "4. Save to gallery, share, or download\\\\n\\\\n" +
      "**Your plan determines your power:**\\\\n" +
      "🔹 **Free:** 10 generations/mo, 512×512, with watermark\\\\n" +
      "🔸 **Pro ($9.99/mo):** 100 HD generations, no watermark, commercial license\\\\n" +
      "💎 **Studio ($24.99/mo):** Unlimited generations, 4K export, API access, team collab\\\\n\\\\n" +
      "🔥 **Launch Week Special:** All annual plans save 20%. Get Studio for just $19.99/mo billed annually.\\\\n\\\\n" +
      "Your first generation is free. Try it now 👇",
    cta: "Start Creating — Free Tier",
    ctaLink: "/dashboard/create",
    targetAudience:
      "All users — both existing (who previously could only view/share art) and new visitors attracted by the generation feature. Free-tier users hitting the 10-gen cap are highest upgrade intent.",
  },

  referralProgram: {
    headline: "Launch Week: Share the Power of Creation 🤝",
    body:
      "Generation is live, and it's best enjoyed with friends. Bring a fellow creator to AniVerse and you both win big. 🎁\\\\n\\\\n" +
      "🤝 **How it works:**\\\\n" +
      "1. Share your unique referral link with a friend\\\\n" +
      "2. They sign up (and experience the new generation feature!)\\\\n" +
      "3. You earn **$10 in credits** (Launch Week DOUBLE bonus!)\\\\n" +
      "4. They get 20% off their first month\\\\n\\\\n" +
      "🎯 **Launch Week Challenge:** First 10 referrers this week earn DOUBLE ($10/referral instead of $5)!\\\\n\\\\n" +
      "Up to 10 referrals per month — redeem credits at $20 minimum. With the new generation feature, there's never been a better time to invite friends.",
    rewardDescription:
      "Launch Week DOUBLE bonus: $10 per referral (normally $5, max 10/mo). Friend gets 20% off first month.",
    cta: "Get Your Referral Link →",
    ctaLink: "/dashboard/referrals",
  },

  coinPromo: {
    headline: "Need More Generations? Fuel Your Creativity 🪙",
    body:
      "Hit your free tier limit but still in a creative flow? AniVerse Coins give you extra generations instantly.\\\\n\\\\n" +
      "🔥 **Launch Week Pricing:**\\\\n" +
      "• Starter Pack: 10 coins — $1.99\\\\n" +
      "• Creator Pack: 50 coins + 5 FREE — $7.99\\\\n" +
      "• Pro Pack: 100 coins + 15 FREE — $14.99 ← **Best value**\\\\n" +
      "• Mega Pack: 500 coins + 100 FREE — $59.99\\\\n\\\\n" +
      "Coins never expire. Use them for extra generations, premium style unlocks, " +
      "or exclusive marketplace items.\\\\n\\\\n" +
      "💡 **Pro tip:** Stack coins with a Pro subscription for maximum creative output! " +
      "Pro gives you 100 gens + coins extend beyond that.",
    cta: "Buy Coins & Create More",
    ctaLink: "/dashboard/coins",
  },

  socialSnippets: {
    twitter: [
      "🚀 BREAKING: AI anime generation is NOW LIVE on AniVerse!\\\\n\\\\nGenerate stunning anime art directly in your browser. 16 style presets. One click. Zero setup.\\\\n\\\\n🎨 Ghibli, Cyberpunk, Retro 90s, Vaporwave + 12 more\\\\n✨ Free tier: 10 generations\\\\n💎 Pro: HD, no watermark, $9.99/mo\\\\n\\\\nTry it now 👇\\\\n#AniVerse #AIAnime #GenerativeAI",
      "Your wait is over 🎉\\\\n\\\\nAniVerse now generates AI anime art right in your browser. No external tools, no API keys, no tech skills needed.\\\\n\\\\nPick a style → Describe your scene → Create instantly.\\\\n\\\\n16 presets including Ghibli, Cyberpunk, Vaporwave, Pastel Goth, and Retro 90s.\\\\n\\\\nFree to start 👇\\\\n#AniVerse #AIArt #Anime #DigitalArt",
      "Launch Week DOUBLE referral bonus! 🚀\\\\n\\\\nGeneration is live and we're celebrating. First 10 referrers earn $10 per referral (2× normal!).\\\\n\\\\nShare AniVerse's new creation power with a friend and DOUBLE your rewards. 🤝\\\\n\\\\n#AniVerse #ReferralProgram #CreatorEconomy",
    ],
    instagram: [
      "🚀 **ANIVERSE JUST GOT SUPERPOWERS** 🚀\\\\n\\\\n🎨 **AI ANIME GENERATION — NOW LIVE IN BROWSER** 🎨\\\\n\\\\n✨ Create stunning AI anime art directly from your dashboard!\\\\n\\\\n🔥 **16 STYLE PRESETS:**\\\\n• Ghibli-Inspired 🌿\\\\n• Cyberpunk 🌃\\\\n• Retro 90s 📼\\\\n• Vaporwave 🌅\\\\n• Pastel Goth 🖤\\\\n• Monochrome Accent 🎭\\\\n• +10 more!\\\\n\\\\n💎 **PLANS FOR EVERY CREATOR:**\\\\n🔹 Free: 10 gens/mo (try before you buy!)\\\\n🔸 Pro: $9.99/mo — HD, no watermark, commercial license\\\\n💎 Studio: $24.99/mo — unlimited gens, 4K, API, team\\\\n\\\\n🔥 **LAUNCH WEEK:** Annual plans save 20%! Studio for $19.99/mo\\\\n\\\\nLink in bio to start creating 👆\\\\n\\\\n#AniVerse #AIAnime #DigitalArt #AIArt #AnimeArt #GenerativeArt #CreatorEconomy #LaunchWeek",
      "🪙 **LAUNCH WEEK COIN BOOST** 🪙\\\\n\\\\nOut of generations? Keep creating with AniVerse Coins!\\\\n\\\\n💎 100 coins + 15 BONUS — $14.99 (BEST VALUE)\\\\n🔥 50 coins + 5 BONUS — $7.99\\\\n👑 500 coins + 100 BONUS — $59.99\\\\n🚀 Starter: 10 coins — $1.99\\\\n\\\\nCoins never expire. Unlimited creativity.\\\\n\\\\nLinks in bio ⚡\\\\n\\\\n#AniVerse #AIArt #AnimeCommunity #DigitalArt #LaunchWeek",
    ],
    discord: [
      "🎉 **🚀 GENERATION IS LIVE! 🚀** 🎉\\\\n\\\\nThe moment you've been waiting for — AI anime generation is NOW AVAILABLE directly in your AniVerse dashboard!\\\\n\\\\n✨ **What's new:**\\\\n• 🎨 **Create page** — pick from 16 style presets, write prompts, generate instantly\\\\n• 🖼️ **Auto-save** to your personal gallery\\\\n• 📊 **Live usage stats** — track your generations per plan\\\\n\\\\n**Plan limits:**\\\\n🔹 Free: 10 gens/mo (512×512, watermark)\\\\n🔸 Pro ($9.99): 100 gens/mo (HD, no watermark, commercial license)\\\\n💎 Studio ($24.99): Unlimited gens (4K, API, team collab)\\\\n\\\\n🔥 **Launch Week special:** Annual plans save 20%!\\\\n\\\\nTry it now in your dashboard → /dashboard/create\\\\nType `/create` to start generating! 🎨",
      "🤝 **LAUNCH WEEK: DOUBLE REFERRAL BONUS!** 🤝\\\\n\\\\nTo celebrate the generation launch, we're DOUBLING referral rewards!\\\\n\\\\n💰 **$10 per referral** (normally $5) — first 10 referrers only!\\\\n\\\\nHere's how:\\\\n1. Grab your unique referral link from Dashboard → Settings\\\\n2. Share with a friend who'd love AI anime creation\\\\n3. They sign up and generate their first artwork\\\\n4. You earn DOUBLE credits!\\\\n\\\\nThis is the best time ever to invite friends. Don't miss out! 🚀",
    ],
  },

  emailCampaign: {
    subject: "🚀 You can now generate AI anime art inside AniVerse!",
    previewText:
      "16 style presets, one click, zero setup. Plus: Launch Week special pricing and double referral rewards.",
    body:
      "Hi {{name}},\\\\n\\\\n" +
      "We have BIG news. 🎉\\\\n\\\\n" +
      "**Starting today, you can generate AI anime artwork directly inside AniVerse.** " +
      "No external tools, no API keys, no technical setup. Just your imagination and our 16 curated style presets.\\\\n\\\\n" +
      "---\\\\n\\\\n" +
      "**🎨 How to create your first artwork:**\\\\n\\\\n" +
      "1. Go to your **Dashboard → Create**\\\\n" +
      "2. Choose from **16 style presets**: Ghibli, Cyberpunk, Retro 90s, " +
      "Vaporwave, Pastel Goth, Monochrome Accent, and more\\\\n" +
      "3. Describe your scene (e.g., \"a samurai under cherry blossoms at sunset\") " +
      "or use our prompt templates\\\\n" +
      "4. Click **Generate** — your artwork appears in seconds!\\\\n" +
      "5. Save to gallery, share with the community, or download\\\\n\\\\n" +
      "---\\\\n\\\\n" +
      "**📊 Your Plan = Your Power**\\\\n\\\\n" +
      "| Feature | Free | Pro ($9.99/mo) | Studio ($24.99/mo) |\\\\n" +
      "|---------|------|----------------|-------------------|\\\\n" +
      "| Generations | 10/mo | 100/mo | Unlimited |\\\\n" +
      "| Resolution | 512×512 | 1024×1024 HD | 2048×2048 4K |\\\\n" +
      "| Watermark | Yes | No | No |\\\\n" +
      "| Commercial License | ❌ | ✅ | ✅ + Resale |\\\\n" +
      "| API Access | ❌ | ❌ | ✅ 1000 req/day |\\\\n" +
      "| Team Collab | ❌ | ❌ | ✅ Up to 5 |\\\\n\\\\n" +
      "🔥 **Launch Week Special:** All annual plans save 20%! " +
      "Get Studio for just $19.99/mo billed annually.\\\\n\\\\n" +
      "---\\\\n\\\\n" +
      "**🤝 DOUBLE REFERRAL REWARDS — THIS WEEK ONLY**\\\\n\\\\n" +
      "To celebrate, we're doubling referral bonuses! " +
      "Earn **$10 per referral** (normally $5) for the first 10 referrals. " +
      "Your friend also gets 20% off their first month.\\\\n\\\\n" +
      "👉 [Start Creating Now]({{create_link}})\\\\n" +
      "👉 [See Plans & Pricing]({{pricing_link}})\\\\n" +
      "👉 [Get Your Referral Link (Double Bonus!)]({{referral_link}})\\\\n\\\\n" +
      "Our mission is to make anime creation accessible to everyone. " +
      "Today, we took a huge step forward. We can't wait to see what you create. 🌀\\\\n\\\\n" +
      "— The AniVerse Team 🚀\\\\n\\\\n" +
      "P.S. Your first generation is free — try it now and see the magic!",
  },
};

export default promoCampaign;
