/**
 * Promo Campaign Content — July 26, 2026
 *
 * Generated by Agent A9 (Monetization & Growth).
 * Ready-to-use marketing copy for premium upgrades, referral programs,
 * and coin system promotions.
 *
 * Theme: "Level Up Your Art" — Sunday special campaign
 */

export interface PromoCampaign {
  date: string;
  campaignName: string;
  /** Primary CTA for premium upgrade. */
  premiumUpgrade: {
    headline: string;
    subheadline: string;
    body: string;
    cta: string;
    ctaLink: string;
    targetAudience: string;
  };
  /** Referral program copy. */
  referralProgram: {
    headline: string;
    body: string;
    rewardDescription: string;
    cta: string;
    ctaLink: string;
  };
  /** Coin system promotion. */
  coinPromo: {
    headline: string;
    body: string;
    cta: string;
    ctaLink: string;
  };
  /** Social media promo snippets. */
  socialSnippets: {
    twitter: string[];
    instagram: string[];
    discord: string[];
  };
  /** Email marketing copy. */
  emailCampaign: {
    subject: string;
    previewText: string;
    body: string;
  };
}

export const promoCampaign: PromoCampaign = {
  date: "2026-07-26",
  campaignName: "Level Up Your Art — Sunday Creator Special",

  premiumUpgrade: {
    headline: "Your Art Deserves the Best Canvas",
    subheadline:
      "From HD generations to commercial licensing — unlock your full creative potential with AniVerse Pro.",
    body:
      "Every artist starts somewhere, but the best creators know when to level up. 🚀\\n\\n" +
      "You've been creating amazing AI anime art on our free plan. Imagine what you could do with:\\n\\n" +
      "🎨 **100 generations/month** — 10× more canvas space\\n" +
      "🖼️ **HD 1024×1024 resolution** — every detail crisp and clear\\n" +
      "🚫 **No watermark** — your brand, not ours\\n" +
      "📜 **Commercial license** — sell your art with confidence\\n" +
      "⚡ **Priority queue** — skip the line, create faster\\n\\n" +
      "💡 **NEW:** Studio plan now just $19.99/mo (was $24.99)! Unlimited generations, 4K export, " +
      "API access, and team collaboration for power creators and small studios.\\n\\n" +
      "Sunday special: All annual plans save 20% — lock in the best rate today.",
    cta: "Upgrade to Pro — $9.99/mo",
    ctaLink: "/register?plan=pro",
    targetAudience:
      "Free-tier users with 5+ generations, active gallery posters, and users who hit the generation limit.",
  },

  referralProgram: {
    headline: "Bring a Friend, Earn Credits",
    body:
      "Creators thrive together. Share AniVerse with a fellow artist and you both win. 🎁\\n\\n" +
      "🤝 **How it works:**\\n" +
      "1. Share your unique referral link\\n" +
      "2. Friend signs up for Pro or Studio\\n" +
      "3. You get $5 in AniVerse credits\\n" +
      "4. They get 20% off their first month\\n\\n" +
      "📈 **Pro tip:** Share your referral link in your art social bio. " +
      "Our top referrer earned $50 in credits last week!\\n\\n" +
      "Up to 10 referrals per month — redeem credits at $20 minimum.",
    rewardDescription:
      "You earn $5 credits per referral (max 10/mo). Your friend gets 20% off their first month.",
    cta: "Get Your Referral Link →",
    ctaLink: "/dashboard/referrals",
  },

  coinPromo: {
    headline: "More Generations, More Inspiration 🪙",
    body:
      "Hit your generation cap but still creating? Top up with AniVerse Coins and keep the inspiration flowing.\\n\\n" +
      "🔥 **Today's best deals:**\\n" +
      "• Starter Pack: 10 coins — $1.99\\n" +
      "• Creator Pack: 50 coins + 5 FREE — $7.99\\n" +
      "• Pro Pack: 100 coins + 15 FREE — $14.99 ← **Best value**\\n" +
      "• Mega Pack: 500 coins + 100 FREE — $59.99\\n\\n" +
      "Coins never expire. Use them for extra generations, premium style unlocks, " +
      "or exclusive marketplace items.",
    cta: "Buy Coins",
    ctaLink: "/dashboard/coins",
  },

  socialSnippets: {
    twitter: [
      "Sunday = Funday. Level up your AI anime art game with AniVerse Pro 🚀\\n\\n✅ HD generations\\n✅ No watermark\\n✅ Commercial license\\n✅ Priority queue\\n\\nFrom $9.99/mo 👇\\n#AniVerse #AIAnime #DigitalArt #CreatorLife",
      "Big news: Studio plan is now $19.99/mo (was $24.99)! 🎉\\n\\nUnlock unlimited generations, 4K export, API access, and team collab for less.\\n\\nPerfect for power creators and small studios 💪\\n\\naniverse-one-khaki.vercel.app\\n#AIArt #AnimeCreators",
      "Refer a friend to AniVerse and DOUBLE the creativity 🎁\\n\\n👉 You get $5 in credits\\n👉 They get 20% off first month\\n\\nShare the art love and earn rewards!\\n\\n#ReferralProgram #AniVerse #CreatorEconomy",
    ],
    instagram: [
      "🎨 **LEVEL UP YOUR ART THIS SUNDAY** 🎨\\n\\nYou've been creating — now it's time to go PRO.\\n\\n✨ WHAT YOU GET:\\n✅ HD 1024×1024 resolution\\n✅ 100 generations/month (10× free)\\n✅ No watermark — ever\\n✅ Commercial license included\\n✅ Priority generation queue\\n\\n💎 STUDIO PLAN UPDATE: Now $19.99/mo!\\nUnlimited gens + 4K export + API access\\n\\n🔥 Annual plans save 20%\\n\\nLink in bio to upgrade 🔗\\n\\n#AniVerse #AIAnime #DigitalArt #AnimeArt #CreatorEconomy #ArtSunday",
      "🪙 **SUNDAY COIN BOOST** 🪙\\n\\nNeed extra generations this weekend?\\n\\n💎 100 coins + 15 BONUS — $14.99\\n🔥 50 coins + 5 BONUS — $7.99\\n👑 500 coins + 100 BONUS — $59.99\\n\\nCoins never expire! Link in bio ⚡\\n\\n#AniVerse #AIArt #AnimeCommunity #DigitalCreators #SundayVibes",
    ],
    discord: [
      "🌞 **Sunday Special — Level Up Your Art!** 🌞\\n\\nThis week's highlights:\\n• 🎨 **Pro plan** — HD gens, no watermark, commercial license — $9.99/mo\\n• 💎 **Studio plan now $19.99/mo** (was $24.99!) — unlimited gens, 4K, API\\n• 🪙 **Coin packs** — 100+15 bonus for $14.99 (best value)\\n• 🤝 **Referral rewards** — $5 per friend referral\\n\\nType `/upgrade` to see plans or visit the dashboard! 🚀",
      "🤝 **Referral Program — Double the Creativity!** 🤝\\n\\nShare AniVerse with a friend and you BOTH win:\\n💰 **You** → $5 in credits\\n🎁 **Friend** → 20% off first month\\n\\nMax 10 referrals/month. Check your referral link in dashboard settings!\\n\\n👉 *Pro tip: Add your link to your social bio!*",
    ],
  },

  emailCampaign: {
    subject: "Your Sunday creativity boost — Pro features unlocked 🚀",
    previewText:
      "HD generations, no watermark, and now Studio at $19.99/mo — your art deserves it",
    body:
      "Hi {{name}},\\n\\n" +
      "Happy Sunday! ☀️ We hope you've been creating amazing art this week.\\n\\n" +
      "Here's something exciting: we've updated our pricing to make it even easier to " +
      "unlock your full creative potential.\\n\\n" +
      "**📢 What's new:**\\n\\n" +
      "💎 **Studio plan now $19.99/mo** (was $24.99) — unlimited generations, 4K resolution, " +
      "API access, and team collaboration for up to 5 members. Perfect for small studios " +
      "and power creators!\\n\\n" +
      "🎨 **Pro plan — $9.99/mo** — HD 1024×1024, 100 generations/month, no watermark, " +
      "commercial license, priority queue.\\n\\n" +
      "🪙 **Coin packs** — Need a quick top-up? 100 coins + 15 bonus for just $14.99.\\n\\n" +
      "🤝 **Referral rewards** — Share AniVerse and earn $5 in credits per referral!\\n\\n" +
      "---\\n\\n" +
      "**Why upgrade?** Here's what our Pro users are saying:\\n\\n" +
      "> \\\"The HD resolution is a game-changer. My prints look incredible.\\\" — @SakuraStudio\\n\\n" +
      "> \\\"I was hesitant about the cost, but the commercial license alone paid for itself " +
      "in my first month.\\\" — @NeonWeaver\\n\\n" +
      "---\\n\\n" +
      "👉 [See All Plans & Pricing]({{pricing_link}})\\n\\n" +
      "👉 [Get Your Referral Link]({{referral_link}})\\n\\n" +
      "Keep creating, stay inspired.\\n\\n" +
      "— The AniVerse Team 🌀\\n\\n" +
      "P.S. Annual plans save 20% — lock in the best rate today!",
  },
};

export default promoCampaign;
