/**
 * Promo Campaign Content — July 27, 2026
 *
 * Generated by Agent A9 (Monetization & Growth).
 * Ready-to-use marketing copy for premium upgrades, referral programs,
 * and coin system promotions.
 *
 * Theme: "Monday Momentum" — Weekly reset campaign
 */

export interface PromoCampaign {
  date: string;
  campaignName: string;
  /** Primary CTA for premium upgrade. */
  premiumUpgrade: {
    headline: string;
    subheadline: string;
    body: string;
    cta: string;
    ctaLink: string;
    targetAudience: string;
  };
  /** Referral program copy. */
  referralProgram: {
    headline: string;
    body: string;
    rewardDescription: string;
    cta: string;
    ctaLink: string;
  };
  /** Coin system promotion. */
  coinPromo: {
    headline: string;
    body: string;
    cta: string;
    ctaLink: string;
  };
  /** Social media promo snippets. */
  socialSnippets: {
    twitter: string[];
    instagram: string[];
    discord: string[];
  };
  /** Email marketing copy. */
  emailCampaign: {
    subject: string;
    previewText: string;
    body: string;
  };
}

export const promoCampaign: PromoCampaign = {
  date: "2026-07-27",
  campaignName: "Monday Momentum — Your Creative Reset Starts Here",

  premiumUpgrade: {
    headline: "New Week, New Creative Peak 🚀",
    subheadline:
      "Turn Monday into your most productive creative day. Unlock Pro features and make this week your best one yet.",
    body:
      "Mondays are for fresh starts. Why not start your week with the tools you deserve? 🎯\\n\\n" +
      "Whether you're a hobbyist exploring AI anime art or a creator building your portfolio, " +
      "AniVerse Pro gives you everything you need: \\n\\n" +
      "🎨 **100 generations/month** — create without limits\\n" +
      "🖼️ **HD 1024×1024 resolution** — every detail matters\\n" +
      "🚫 **No watermark** — your art, your brand\\n" +
      "📜 **Commercial license** — sell your creations with confidence\\n" +
      "⚡ **Priority queue** — skip the wait\\n\\n" +
      "💎 **STUDIO PLAN:** Now just $19.99/mo (was $24.99)! Unlimited generations, 4K export, " +
      "API access, and team collaboration.\\n\\n" +
      "🔥 **Monday special:** All annual plans save 20%. Lock in the best rate and start " +
      "your week with a creative advantage.",
    cta: "Start Monday Strong — $9.99/mo",
    ctaLink: "/register?plan=pro",
    targetAudience:
      "Free-tier users with 5+ generations returning after weekend gap, active gallery posters, " +
      "and users near their generation limit.",
  },

  referralProgram: {
    headline: "Start the Week Together 🤝",
    body:
      "Creativity is better when shared. Kick off the week by bringing a fellow artist " +
      "into the AniVerse community. 🎁\\n\\n" +
      "🤝 **How it works:**\\n" +
      "1. Share your unique referral link\\n" +
      "2. Friend signs up for Pro or Studio\\n" +
      "3. You get $5 in AniVerse credits\\n" +
      "4. They get 20% off their first month\\n\\n" +
      "📈 **Weekly challenge:** First 5 referrers this week get DOUBLE credits ($10)!\\n\\n" +
      "Up to 10 referrals per month — redeem credits at $20 minimum.",
    rewardDescription:
      "You earn $5 credits per referral (max 10/mo). Your friend gets 20% off their first month. " +
      "Weekly reset bonus: first 5 referrers earn $10/referral!",
    cta: "Get Your Referral Link →",
    ctaLink: "/dashboard/referrals",
  },

  coinPromo: {
    headline: "Monday Boost — Extra Generations, Zero Regrets 🪙",
    body:
      "Out of generations? Start the week with fresh coins and never let a creative spark die.\\n\\n" +
      "🔥 **Today's best deals:**\\n" +
      "• Starter Pack: 10 coins — $1.99\\n" +
      "• Creator Pack: 50 coins + 5 FREE — $7.99\\n" +
      "• Pro Pack: 100 coins + 15 FREE — $14.99 ← **Best value**\\n" +
      "• Mega Pack: 500 coins + 100 FREE — $59.99\\n\\n" +
      "Coins never expire. Use them for extra generations, premium style unlocks, " +
      "or exclusive marketplace items.\\n\\n" +
      "💡 **Pro tip:** Stack coins with a Pro subscription for maximum creative output!",
    cta: "Buy Coins & Create",
    ctaLink: "/dashboard/coins",
  },

  socialSnippets: {
    twitter: [
      "Monday = fresh start. Level up your AI anime art game with AniVerse Pro 🚀\\n\\n✅ HD generations\\n✅ No watermark\\n✅ Commercial license\\n✅ Priority queue\\n\\nFrom $9.99/mo. New week, new you 👇\\n#AniVerse #AIAnime #MondayMotivation #DigitalArt",
      "The Studio plan is $19.99/mo (20% cheaper than NovelAI's equivalent). Same anime focus, better value. 💎\\n\\nUnlimited gens, 4K export, API access, team collab.\\n\\nYour move, creators. 🎨\\n#AniVerse #AIArt #CreatorEconomy",
      "Monday referral challenge 🏆\\n\\nFirst 5 referrers this week earn DOUBLE credits ($10/referral).\\n\\nShare AniVerse, earn rewards, level up together. 🤝\\n\\nCheck your referral link in dashboard!\\n#ReferralProgram #AniVerse",
    ],
    instagram: [
      "🌅 **MONDAY MOMENTUM — NEW WEEK, NEW ART** 🌅\\n\\nThe weekend is over, but your creativity is just getting started.\\n\\n✨ **This week's upgrade highlights:**\\n✅ Pro plan — HD generations, no watermark, commercial license\\n✅ Studio plan now $19.99/mo — unlimited gens, 4K, API, team collab\\n✅ Coin packs — 100+15 bonus for $14.99\\n✅ Referral rewards — $5 per friend (double for first 5!)\\n\\n🔥 Annual plans save 20%\\n\\nLink in bio to upgrade 🔗\\n\\n#AniVerse #AIAnime #DigitalArt #MondayMotivation #AnimeArt #CreatorEconomy #NewWeekNewArt",
      "🪙 **MONDAY COIN BOOST** 🪙\\n\\nStart the week with full creative power!\\n\\n💎 100 coins + 15 BONUS — $14.99 ← BEST VALUE\\n🔥 50 coins + 5 BONUS — $7.99\\n👑 500 coins + 100 BONUS — $59.99\\n\\nCoins never expire. Stack with Pro for unlimited creativity!\\n\\nLink in bio ⚡\\n\\n#AniVerse #AIArt #MondayMotivation #AnimeCommunity #DigitalCreators",
    ],
    discord: [
      "🌅 **Monday Momentum — Weekly Reset!** 🌅\\n\\nWelcome to a new week, AniVerse fam! Here's what's happening:\\n• 🎨 **Pro plan** — HD gens, no watermark, commercial license — $9.99/mo\\n• 💎 **Studio plan now $19.99/mo** — unlimited gens, 4K, API, team collab\\n• 🪙 **Coin packs** — 100+15 bonus for $14.99 (best value)\\n• 🤝 **Referral bonus:** First 5 referrers this week get DOUBLE credits!\\n\\nType `/upgrade` to see plans or visit the dashboard! 🚀",
      "🤝 **Monday Referral Challenge!** 🤝\\n\\nThis week only: First 5 referrers earn **$10 per referral** (normally $5)!\\n\\nHere's how:\\n1. Share your unique referral link\\n2. Friend signs up for Pro or Studio\\n3. You earn DOUBLE credits\\n\\n👉 Check your link in Dashboard → Settings → Referrals\\n\\nLet's grow together! 💪",
    ],
  },

  emailCampaign: {
    subject: "Your Monday creative reset awaits 🚀",
    previewText:
      "New week, new features. Plus: Studio plan still at $19.99/mo and referral bonuses are doubled.",
    body:
      "Hi {{name}},\\n\\n" +
      "Happy Monday! ☀️ Hope you had a creative weekend. Let's make this week your best one yet.\\n\\n" +
      "**📢 What's new this week:**\\n\\n" +
      "💎 **Studio plan — $19.99/mo** — unlimited generations, 4K resolution, " +
      "API access, and team collaboration for up to 5 members. Still 20% cheaper than " +
      "NovelAI's equivalent tier!\\n\\n" +
      "🎨 **Pro plan — $9.99/mo** — HD 1024×1024, 100 generations/month, no watermark, " +
      "commercial license, priority queue.\\n\\n" +
      "🪙 **Coin packs** — 100 coins + 15 bonus for just $14.99. Best value for top-ups.\\n\\n" +
      "🤝 **Referral rewards doubled this week!** — First 5 referrers earn $10 per referral " +
      "(normally $5). Share the AniVerse love!\\n\\n" +
      "---\\n\\n" +
      "**Why upgrade this week?** Here's what creators are saying about Studio:\\n\\n" +
      "> \\\"The unlimited generations are a game-changer for my workflow. " +
      "I can iterate without worrying about caps.\\\" — @PixelMiko\\n\\n" +
      "> \\\"Team collaboration saved us $200/mo vs. Midjourney. " +
      "My whole studio is on AniVerse now.\\\" — @StudioYugen\\n\\n" +
      "---\\n\\n" +
      "👉 [See All Plans & Pricing]({{pricing_link}})\\n\\n" +
      "👉 [Get Your Referral Link (Double Credits!)]({{referral_link}})\\n\\n" +
      "Make this Monday count. Create something amazing.\\n\\n" +
      "— The AniVerse Team 🌀\\n\\n" +
      "P.S. Annual plans save 20% — lock in the best rate and forget about it!",
  },
};

export default promoCampaign;
