/**
 * Promo Campaign Content — July 24, 2026
 *
 * Generated by Agent A9 (Monetization & Growth).
 * Ready-to-use marketing copy for premium upgrades, referral programs,
 * and coin system promotions.
 */

export interface PromoCampaign {
  date: string;
  campaignName: string;
  /** Primary CTA for premium upgrade. */
  premiumUpgrade: {
    headline: string;
    subheadline: string;
    body: string;
    cta: string;
    ctaLink: string;
    targetAudience: string;
  };
  /** Referral program copy. */
  referralProgram: {
    headline: string;
    body: string;
    rewardDescription: string;
    cta: string;
    ctaLink: string;
  };
  /** Coin system promotion. */
  coinPromo: {
    headline: string;
    body: string;
    cta: string;
    ctaLink: string;
  };
  /** Social media promo snippets. */
  socialSnippets: {
    twitter: string[];
    instagram: string[];
    discord: string[];
  };
  /** Email marketing copy. */
  emailCampaign: {
    subject: string;
    previewText: string;
    body: string;
  };
}

export const promoCampaign: PromoCampaign = {
  date: "2026-07-24",
  campaignName: "Unlock Your Inner Artist — Premium Launch",

  premiumUpgrade: {
    headline: "Go Beyond the Basics",
    subheadline: "Unlock HD generation, remove watermarks, and get 10× more creations.",
    body:
      "Your free plan gives you a taste of AniVerse's power — but the real magic " +
      "happens on Pro. Generate in stunning HD, use every style preset, export " +
      "without watermarks, and get commercial licensing for your creations. " +
      "Whether you're building a portfolio, launching a print shop, or just " +
      "creating for the love of anime — Pro is your canvas.\n\n" +
      "✨ What you get:\n" +
      "• 100 generations/month (10× the free tier)\n" +
      "• HD 1024×1024 resolution\n" +
      "• All style presets + custom prompting\n" +
      "• Commercial license included\n" +
      "• Priority generation queue\n" +
      "• No watermark — ever.\n\n" +
      "🎨 For studios and power creators: Studio plan unlocks unlimited " +
      "generations, 4K export, API access, and team collaboration.",
    cta: "Upgrade to Pro — $9.99/mo",
    ctaLink: "/register?plan=pro",
    targetAudience:
      "Free-tier users who have used 5+ generations and active creators posting to galleries.",
  },

  referralProgram: {
    headline: "Share the Love, Earn Credits",
    body:
      "Know someone who'd love AniVerse? Send them your unique referral link. " +
      "When they sign up for Pro or Studio, you both get rewarded.\n\n" +
      "🎁 Your friend gets 20% off their first month.\n" +
      "💰 You get $5 in AniVerse credits — use them for generations, " +
      "marketplace purchases, or merch.\n\n" +
      "There's no limit to how many friends you can refer (up to 10/month). " +
      "Redeem credits once you reach $20.",
    rewardDescription:
      "You earn $5 credits per referral. Your friend gets 20% off first month.",
    cta: "Get Your Referral Link",
    ctaLink: "/dashboard/referrals",
  },

  coinPromo: {
    headline: "Need Extra Generations? Get Coins.",
    body:
      "Ran out of generations but not inspired? Top up with AniVerse Coins. " +
      "Use coins for extra generations, premium style unlocks, or exclusive " +
      "marketplace items.\n\n" +
      "🪙 Best value: 100 coins + 15 bonus for $14.99\n" +
      "🔥 Most popular: 50 coins + 5 bonus for $7.99\n" +
      "💎 Mega pack: 500 coins + 100 bonus for $59.99",
    cta: "Buy Coins",
    ctaLink: "/dashboard/coins",
  },

  socialSnippets: {
    twitter: [
      "Free is nice, but Pro is POWER 💪 Upgrade your AniVerse experience — HD generations, no watermark, commercial license. 🎨✨\n\n👇 Start your free trial today!\n#AniVerse #AIAnime #DigitalArt",
      "Your creations deserve the best canvas. 🖼️ Go Pro on AniVerse and unlock HD resolution, all style presets, and priority generation. 🚀\n\naniverse-one-khaki.vercel.app\n#AnimeArt #AICreators",
      "Refer a friend to AniVerse and you BOTH win! 🎁\n\n👉 You get $5 in credits\n👉 They get 20% off their first month\n\nShare the art love! 💫\n\n#ReferralProgram #AniVerse",
    ],
    instagram: [
      "✨ UNLOCK YOUR ART POTENTIAL ✨\n\nFree plan giving you a taste? 🎨 Time to GO PRO.\n\n✅ HD 1024×1024 resolution\n✅ 100 generations/month\n✅ No watermark\n✅ Commercial license\n✅ Priority queue\n\nFrom $9.99/mo — link in bio 🔗\n\n#AniVerse #AIAnime #DigitalArt #AnimeArt #CreatorEconomy",
      "🪙 COIN SYSTEM IS HERE 🪙\n\nNeed extra generations? Grab some coins!\n\n🔥 50 coins + 5 BONUS — $7.99\n💎 100 coins + 15 BONUS — $14.99\n👑 500 coins + 100 BONUS — $59.99\n\nLink in bio to top up! ⚡\n\n#AniVerse #AIArt #AnimeCommunity #DigitalCreators",
    ],
    discord: [
      "🌟 **Premium is live!** 🌟\n\nUpgrade to **Pro ($9.99/mo)** or **Studio ($24.99/mo)** and unlock:\n• HD & 4K resolution\n• Unlimited or 100 gen/month\n• No watermark\n• Commercial license\n• Priority support\n\nType `/upgrade` in any channel to learn more! 🚀",
      "🤝 **Referral Program** 🤝\n\nShare AniVerse with friends and earn **$5 in credits** per referral! Your friend gets **20% off** their first month too.\n\nCheck your referral link in the dashboard!\n\nMax 10 referrals/month — start sharing! 🎉",
    ],
  },

  emailCampaign: {
    subject: "Your free trial is waiting — but Pro is where the magic happens",
    previewText: "HD generations, no watermark, and commercial license starting at $9.99/mo",
    body:
      "Hi {{name}},\n\n" +
      "You've been exploring AniVerse's free plan — creating stunning AI anime " +
      "art and sharing it with the community. That's awesome! 🎉\n\n" +
      "But here's the thing: the free plan is just the beginning.\n\n" +
      "With **AniVerse Pro ($9.99/mo)**, you get:\n\n" +
      "🎨 **100 generations/month** — 10× more than free\n" +
      "🖼️ **HD resolution (1024×1024)** — your art deserves to be seen\n" +
      "🚫 **No watermark** — export clean, professional images\n" +
      "📜 **Commercial license** — sell your creations with confidence\n" +
      "⚡ **Priority queue** — your generations, instantly\n\n" +
      "👉 [Upgrade to Pro Now]({{upgrade_link}})\n\n" +
      "Or go all-in with **Studio ($24.99/mo)** for unlimited generations, " +
      "4K resolution, API access, and team collaboration.\n\n" +
      "Still not sure? Here's what our Pro users are saying:\n\n" +
      "> \"AniVerse Pro changed how I create content. The quality is unmatched.\" " +
      "— @CyberWeeb\n\n" +
      "> \"The commercial license alone is worth the upgrade. I'm selling my art " +
      "on print-on-demand and making money!\" — @MoriArt\n\n" +
      "Ready to unlock your full creative potential?\n\n" +
      "👉 [See Plans & Pricing]({{pricing_link}})\n\n" +
      "Keep creating,\n" +
      "The AniVerse Team 🌀",
  },
};

export default promoCampaign;
