/**
 * Promo Campaign Content — July 25, 2026
 *
 * Generated by Agent A9 (Monetization & Growth).
 * Ready-to-use marketing copy for premium upgrades, referral programs,
 * and coin system promotions.
 *
 * Inspired by today's trending styles (Vaporwave, Retro 90s, Art Nouveau,
 * Pastel Goth) and A7 social media campaign.
 */

export interface PromoCampaign {
  date: string;
  campaignName: string;
  /** Primary CTA for premium upgrade. */
  premiumUpgrade: {
    headline: string;
    subheadline: string;
    body: string;
    cta: string;
    ctaLink: string;
    targetAudience: string;
  };
  /** Referral program copy. */
  referralProgram: {
    headline: string;
    body: string;
    rewardDescription: string;
    cta: string;
    ctaLink: string;
  };
  /** Coin system promotion. */
  coinPromo: {
    headline: string;
    body: string;
    cta: string;
    ctaLink: string;
  };
  /** Social media promo snippets. */
  socialSnippets: {
    twitter: string[];
    instagram: string[];
    discord: string[];
  };
  /** Email marketing copy. */
  emailCampaign: {
    subject: string;
    previewText: string;
    body: string;
  };
}

export const promoCampaign: PromoCampaign = {
  date: "2026-07-25",
  campaignName: "Vaporwave Dreams — Premium Summer Sale",

  premiumUpgrade: {
    headline: "Create Without Limits",
    subheadline:
      "From VHS nostalgia to 4K masterpieces — unlock every style with AniVerse Pro.",
    body:
      "You've seen what AniVerse can do on the free plan. Now imagine creating in " +
      "stunning HD, with every style preset unlocked — from Retro '90s cel-shaded " +
      "vibes to Ghibli-inspired landscapes, Vaporwave dreamscapes, and Art Nouveau " +
      "elegance.\n\n" +
      "✨ **Pro ($9.99/mo)** unlocks:\n" +
      "• 100 generations/month (10× the free tier)\n" +
      "• HD 1024×1024 resolution — every detail pops\n" +
      "• All 11 style presets + custom prompting\n" +
      "• Commercial license — sell your creations\n" +
      "• Priority queue — no waiting\n" +
      "• Export without watermark\n\n" +
      "🏢 **Studio ($24.99/mo)** for power users:\n" +
      "• Unlimited generations\n" +
      "• 4K resolution (2048×2048)\n" +
      "• Full model control + negative prompts\n" +
      "• API access (1,000 req/day)\n" +
      "• Team collaboration (up to 5)\n\n" +
      "Today's trending styles — Vaporwave, '90s Retro, Pastel Goth, Art Nouveau — " +
      "are all waiting for you. Don't just browse the gallery. Create your own.",

    cta: "Upgrade to Pro — $9.99/mo",
    ctaLink: "/register?plan=pro",
    targetAudience:
      "Free-tier users with 5+ generations this week, especially those engaging " +
      "with today's Vaporwave/Retro 90s art in the gallery.",
  },

  referralProgram: {
    headline: "Bring a Friend, Unlock More Art",
    body:
      "Great art is better shared. When you refer a friend to AniVerse, you both win.\n\n" +
      "🎁 **Your friend gets 20% off their first month** of Pro or Studio.\n" +
      "💰 **You earn $5 in AniVerse credits** — redeem for generations, " +
      "marketplace purchases, or exclusive styles.\n\n" +
      "Share your referral link on social media, Discord, or directly with friends. " +
      "Up to 10 referrals per month, $20 minimum payout.\n\n" +
      "The more creators in our community, the more amazing art we all get to see!",
    rewardDescription:
      "You earn $5 credits per referral. Your friend gets 20% off first month.",
    cta: "Get Your Referral Link",
    ctaLink: "/dashboard/referrals",
  },

  coinPromo: {
    headline: "Extra Generations? Grab Some Coins.",
    body:
      "Hit the limit but still inspired? Top up with AniVerse Coins for " +
      "extra generations, premium style unlocks, or exclusive marketplace items.\n\n" +
      "🪙 **Starter Pack** — 10 coins for $1.99\n" +
      "🔥 **Creator Pack** — 50 coins + 5 BONUS for $7.99 (best value!)\n" +
      "💎 **Pro Pack** — 100 coins + 15 BONUS for $14.99\n" +
      "👑 **Mega Pack** — 500 coins + 100 BONUS for $59.99\n\n" +
      "Coins never expire. Stock up now and create whenever inspiration strikes!",
    cta: "Buy Coins",
    ctaLink: "/dashboard/coins",
  },

  socialSnippets: {
    twitter: [
      "Vaporwave dreams, Retro 90s vibes, Art Nouveau elegance — all in ONE platform. 🎨\\n\\nUnlock every style with AniVerse Pro. From $9.99/mo.\\n\\n👇 Start creating\\naniverse-one-khaki.vercel.app\\n#AniVerse #AIAnime #Vaporwave #DigitalArt",

      "Your free plan is just the beginning. 🚀\\n\\nUpgrade to Pro and get:\\n✅ HD 1024×1024 resolution\\n✅ 100 generations/month\\n✅ No watermark\\n✅ Commercial license\\n✅ Priority queue\\n\\nFrom $9.99/mo → aniverse-one-khaki.vercel.app\\n#AnimeArt #AICreators #ProArtist",

      "Refer a friend = $5 for you + 20% off for them. 🤝\\n\\nDouble the creators, double the art. Share AniVerse today!\\n\\n#ReferralProgram #AniVerse #CreateTogether",
    ],
    instagram: [
      "✨ YOUR ART DESERVES THE BEST CANVAS ✨\\n\\nGoing PRO on AniVerse unlocks:\\n\\n🎨 100 generations/month\\n🖼️ HD 1024×1024 — every detail matters\\n🚫 No watermark — export clean\\n📜 Commercial license included\\n⚡ Priority generation queue\\n\\nFrom $9.99/mo — link in bio 🔗\\n\\nWhich style will YOU create first? Retro 90s? Vaporwave? Ghibli-inspired? Tell us! ⬇️\\n\\n#AniVerse #AIAnime #DigitalArt #AnimeArt #CreatorEconomy #GoPro",

      "🪙 COINS = MORE CREATIVITY 🪙\\n\\nNeed extra generations? We've got you.\\n\\n🔥 50 coins + 5 FREE — $7.99\\n💎 100 coins + 15 FREE — $14.99\\n👑 500 coins + 100 FREE — $59.99\\n\\nCoins never expire! Stock up & create anytime. 🎨\\n\\nLink in bio to grab yours! ⚡\\n\\n#AniVerse #AIArt #AnimeCommunity #DigitalCreators",
    ],
    discord: [
      "🌟 **Premium is live!** 🌟\\n\\nUpgrade to **Pro ($9.99/mo)** or **Studio ($24.99/mo)** and unlock:\\n• HD & 4K resolution\\n• Unlimited or 100 gen/month\\n• No watermark\\n• Commercial license\\n• All 11 style presets\\n• Priority support\\n\\nType `/upgrade` in any channel to learn more! 🚀",

      "🤝 **Referral Program — Share the Art Love!** 🤝\\n\\nRefer a friend and you BOTH win:\\n• You → **$5 in AniVerse credits**\\n• Them → **20% off** first month\\n\\nUp to 10 referrals/month. Check your referral link in /dashboard! 🎉",

      "🎨 **Today's Trending Styles** 🎨\\n\\nVaporwave • Retro 90s • Art Nouveau • Pastel Goth\\n\\nWhich style would you create if you had Pro right now? Drop your answer below! 👇\\n\\n(Psst... Pro members get ALL styles unlocked + HD quality!)",
    ],
  },

  emailCampaign: {
    subject: "Your art deserves more — unlock Pro features today",
    previewText:
      "HD generations, no watermark, all 11 style presets. Starting at $9.99/mo.",
    body:
      "Hi {{name}},\n\n" +
      "You've been exploring AniVerse's free plan, creating AI anime art and " +
      "sharing it with the community. We've seen your creations — and they're amazing! 🎉\n\n" +
      "But did you know there's so much more you can do?\n\n" +
      "With **AniVerse Pro ($9.99/mo)**, you unlock:\n\n" +
      "🎨 **100 generations/month** — 10× more than free\n" +
      "🖼️ **HD resolution (1024×1024)** — make every detail pop\n" +
      "🚫 **No watermark** — export clean, professional images\n" +
      "📜 **Commercial license** — sell your creations with confidence\n" +
      "⚡ **Priority queue** — your generations, instantly\n" +
      "🌈 **All 11 style presets** — from Retro 90s to Ghibli to Vaporwave\n\n" +
      "👉 [Upgrade to Pro Now]({{upgrade_link}})\n\n" +
      "Or go all-in with **Studio ($24.99/mo)** for unlimited generations, " +
      "4K resolution, full model control, API access, and team collaboration.\n\n" +
      "---\n\n" +
      "**Not sure yet? Here's what our community is saying:**\n\n" +
      "> \"AniVerse Pro is incredible. I'm creating art in styles I never thought " +
      "possible with AI. The Vaporwave presets are 🔥\" — @NeonDreamer\n\n" +
      "> \"The commercial license alone is worth it. I've already sold 3 pieces " +
      "on print-on-demand!\" — @MoriArt\n\n" +
      "---\n\n" +
      "**Limited-time offer:** Upgrade to annual billing and save 20% " +
      "(only $7.99/mo for Pro, $19.99/mo for Studio).\n\n" +
      "👉 [See All Plans & Pricing]({{pricing_link}})\n\n" +
      "Keep creating,\n" +
      "The AniVerse Team 🌀\n\n" +
      "P.S. — Refer a friend and you both get rewarded! Share your referral " +
      "link from the dashboard to earn $5 in credits. 🎁",
  },
};

export default promoCampaign;
