/**
 * Daily Community Prompt — July 26, 2026
 *
 * Generated by Agent A8 (Community Engagement & Content Quality)
 * Theme: Retro '90s Anime Revival (aligned with A1 trend research)
 */

export interface CommunityPrompt {
  date: string;
  topic: string;
  question: string;
  description: string;
  platforms: string[];
  hashtags: string[];
}

export interface ReplyTemplate {
  id: string;
  platform: string;
  scenario: string;
  reply: string;
}

export const dailyPrompt: CommunityPrompt = {
  date: "2026-07-26",
  topic: "90s Anime Nostalgia — Which era defined your love for anime?",
  question:
    "🎬 RETRO '90s ANIME NOSTALGIA 🎬\n\nFrom Evangelion to Cowboy Bebop, Sailor Moon to Ghibli's golden era — the '90s gave us some of the most iconic anime ever made.\n\n🔥 Which '90s anime defined YOUR childhood?\n🎨 If you could recreate one scene in AI, which would it be?\n\nShare your pick below and we'll generate it with Retro '90s style on AniVerse! 👇\n\n✨ 10 FREE AI anime generations at aniverse-one-khaki.vercel.app",
  description:
    "Daily discussion prompt aligned with today's Retro '90s anime trend. Encourages nostalgia-driven engagement and cross-promotes AniVerse's Retro '90s style preset. Suitable for Discord daily thread, Twitter/X poll, and Instagram story question sticker.",
  platforms: ["Discord", "Twitter/X", "Instagram Stories"],
  hashtags: [
    "RetroAnime",
    "90sAnime",
    "AnimeNostalgia",
    "AniVerse",
    "AIAnimeArt",
    "CowboyBebop",
    "SailorMoon",
    "Evangelion",
    "Ghibli",
  ],
};

export const replyTemplates: ReplyTemplate[] = [
  {
    id: "rt-001",
    platform: "Instagram",
    scenario:
      "User comments on carousel post — picking a favorite artwork",
    reply:
      "Great choice! 🎨 \"{{artwork}}\" was generated using our {{style}} style preset. Want to create something similar? Try this prompt on AniVerse:\n\n\"{{prompt}}\"\n\n10 free generations waiting for you! Link in bio 🚀",
  },
  {
    id: "rt-002",
    platform: "Instagram",
    scenario:
      "User asks about AI art ethics / how AniVerse works",
    reply:
      "Great question! 🌟 AniVerse uses fine-tuned diffusion models trained on licensed & synthetic data. Every artwork is unique — the AI interprets your prompt fresh each time. We're transparent about our training data and committed to ethical AI practices. Learn more at aniverse-one-khaki.vercel.app/about ✨",
  },
  {
    id: "rt-003",
    platform: "Twitter/X",
    scenario:
      "User shares their own AI art creation inspired by the thread",
    reply:
      "🔥 WHOA, this is incredible! Love how you adapted the {{style}} style with your own creative twist. The {{detail}} really makes it pop!\n\nYou've got serious talent — are you on the AniVerse community gallery yet? Share your portfolio with us! 🎨✨",
  },
  {
    id: "rt-004",
    platform: "Twitter/X",
    scenario:
      "User replies about their favorite '90s anime in the nostalgia thread",
    reply:
      "Ooh, {{anime}} is PEAK '90s! 🔥 The cel-shaded aesthetic, the hand-painted backgrounds — absolute chef's kiss. Makes us want to generate a whole series in that style!\n\nWhich scene from {{anime}} would you want to see reimagined in AI? We'll feature the best ideas in tomorrow's art drop! 👇",
  },
  {
    id: "rt-005",
    platform: "General / Discord",
    scenario:
      "User expresses interest in learning AI anime generation",
    reply:
      "Welcome to the AniVerse family! 🎉 We're so glad you're here!\n\n🚀 Quick start guide:\n1. Head to aniverse-one-khaki.vercel.app\n2. Sign up (free)\n3. Choose a style preset (try Retro '90s!)\n4. Write your prompt\n5. Generate!\n\n💡 Pro tip: Start with \"anime girl/boy with [color] hair, [style] style, cinematic lighting\" for great first results!\n\nShare what you create — we'd love to see it! 🎨✨",
  },
];
