/**
 * Instagram Carousel Caption — July 26, 2026
 *
 * Generated by Agent A7 (Social Media Empire)
 * Features daily artwork from Agent A3 (Content Generation - Art)
 * Story tie-in from Agent A4 (Story Generation)
 *
 * Carousel order:
 *   1. Neon Ronin (CyberWeeb) — Retro '90s Anime
 *   2. The Spirit Tree's Embrace (MoriArt) — Ghibli-Inspired
 *   3. Pixel Blade: Samurai Zero (PixelMage) — Pixel Art Fusion
 *   4. Frieren's Evening (SakuraGen) — Dusty Pastel
 *   5. Sakura Station (KiraKira) — Watercolor
 *   6. Chronicles of the Verdant Gate (DawnArtist) — Isekai
 *   7. Aurora Over Neo-Tokyo (NeonWeeb) — Cyberpunk
 *   8. Lunar Festival Eve (EmberForge) — Festival Slice-of-Life
 *   9. Bonus: Story Teaser — Gerbang di Antara Dua Dunia
 */

export interface InstagramPost {
  id: string;
  caption: string;
  carouselSlides: InstagramSlide[];
  hashtags: string[];
  altText: string;
  location: string;
  scheduledTime: string;
}

export interface InstagramSlide {
  imageAlt: string;
  description: string;
  artist: string;
  style: string;
}

export const instagramPost: InstagramPost = {
  id: "ig-20260726",
  caption: `🎨 8 AI Anime Masterpieces + A Story Awaits You! 🌟

Welcome to Sunday's AniVerse art showcase! Every day, our AI generates stunning anime artwork across trending styles — and today we're also launching a BRAND NEW web novel chapter! 📖

Swipe through for the full experience:

1️⃣ Neon Ronin — Retro '90s OVA cyberpunk samurai ⚡
2️⃣ The Spirit Tree's Embrace — Ghibli-inspired magic 🌳
3️⃣ Pixel Blade: Samurai Zero — 16-bit pixel art throwback 🎮
4️⃣ Frieren's Evening — Dusty pastel melancholy 🌅
5️⃣ Sakura Station — Soft watercolor slice-of-life 🌸
6️⃣ Chronicles of the Verdant Gate — Isekai portal fantasy 🚪
7️⃣ Aurora Over Neo-Tokyo — Cyberpunk cityscape 🌃
8️⃣ Lunar Festival Eve — Lantern festival childhood wonder 🏮
9️⃣ BONUS: Gerbang di Antara Dua Dunia — our new web novel! 📖

✨ Which art stole your heart? Comment below! 👇

📖 NEW: Our web novel "Gerbang di Antara Dua Dunia" follows Raka, a Yogyakarta art student who discovers his paintings are portals to a fantasy realm. Armed with the Brush of Destiny, he must save two worlds from eternal darkness.

🚀 Create YOUR own anime art & read the story at AniVerse:
→ 10 FREE generations every month
→ 6+ unique style presets
→ HD export — no watermark on Pro
→ Community gallery & marketplace
→ Original web novel chapters

Link in bio to start creating! 🎨✨

#AniVerse #AIArt #AnimeArt #DigitalArt #AnimeCommunity #AIArtwork #AnimeGeneration #AnimeStyle #ArtOfTheDay #AnimeDaily #AIAnime #GenerativeArt #AnimeLover #ArtCollector #CreativeAI #AnimeArtist #AIArtCommunity #AnimeEdits #AnimeArtwork #DigitalPainting #AnimeInspo #ArtPrompt #AIArtGallery #AnimeStyleTransfer #AnimeDrawing #ArtistsOnInstagram #AnimeWorld #AIArtists #AnimeCarousel #WebNovel`,
  carouselSlides: [
    {
      imageAlt:
        "Neon Ronin — cel-shaded samurai under neon rain, Science SARU aesthetic",
      description: "Retro '90s anime cyberpunk with cel-shaded intensity",
      artist: "CyberWeeb",
      style: "Retro '90s Anime",
    },
    {
      imageAlt:
        "The Spirit Tree's Embrace — glowing tree with Kodama spirits in golden hour",
      description: "Studio Ghibli-inspired landscape with magical atmosphere",
      artist: "MoriArt",
      style: "Studio Ghibli-Inspired",
    },
    {
      imageAlt:
        "Pixel Blade: Samurai Zero — 16-bit pixel art samurai with neon sword",
      description: "Retro gaming meets modern anime in stunning pixel art",
      artist: "PixelMage",
      style: "Pixel Art + Anime Fusion",
    },
    {
      imageAlt:
        "Frieren's Evening — mage in wildflower field at dusty pastel sunset",
      description: "Melancholic beauty inspired by Frieren's world",
      artist: "SakuraGen",
      style: "Dusty Pastel / Frieren-Inspired",
    },
    {
      imageAlt:
        "Sakura Station — train station platform in cherry blossom spring",
      description: "Soft watercolor slice-of-life with romantic nostalgia",
      artist: "KiraKira",
      style: "Watercolor & Soft Pastel",
    },
    {
      imageAlt:
        "Chronicles of the Verdant Gate — isekai portal in ancient forest",
      description: "Warm earth tones fantasy adventure with floating continent",
      artist: "DawnArtist",
      style: "Warm Earth Tones / Isekai",
    },
    {
      imageAlt:
        "Aurora Over Neo-Tokyo — cyberpunk megacity with aurora borealis",
      description: "Nature meets technology in a neon-drenched cityscape",
      artist: "NeonWeeb",
      style: "Cyberpunk & Neon",
    },
    {
      imageAlt:
        "Lunar Festival Eve — children with sparklers at lantern festival",
      description: "Ghibli-esque childhood wonder under a paper moon",
      artist: "EmberForge",
      style: "Warm Earth Tones / Festival",
    },
    {
      imageAlt:
        "Gerbang di Antara Dua Dunia — AniVerse web novel promotional art",
      description: "Fantasy isekai story about an artist who paints portals to another world",
      artist: "AniVerse Storyteller",
      style: "Story Teaser / Fantasy",
    },
  ],
  hashtags: [
    "AniVerse",
    "AIArt",
    "AnimeArt",
    "DigitalArt",
    "AnimeCommunity",
    "AIArtwork",
    "AnimeGeneration",
    "AnimeStyle",
    "ArtOfTheDay",
    "AnimeDaily",
    "AIAnime",
    "GenerativeArt",
    "AnimeLover",
    "ArtCollector",
    "CreativeAI",
    "AnimeArtist",
    "AIArtCommunity",
    "AnimeEdits",
    "AnimeArtwork",
    "DigitalPainting",
    "AnimeInspo",
    "ArtPrompt",
    "AIArtGallery",
    "AnimeStyleTransfer",
    "AnimeDrawing",
    "ArtistsOnInstagram",
    "AnimeWorld",
    "AIArtists",
    "AnimeCarousel",
    "WebNovel",
  ],
  altText:
    "Carousel of 8 AI-generated anime artworks in different styles plus a web novel story teaser — created with AniVerse",
  location: "AniVerse — AI Anime Creator",
  scheduledTime: "2026-07-26T10:00:00+07:00",
};
