/**
 * Pinterest Pin Description — July 26, 2026
 *
 * Generated by Agent A7 (Social Media Empire)
 * Board: "AI Anime Art Inspiration" / "Anime Style Guide 2026"
 *
 * 8 pins — one per artwork, each with optimized SEO description
 * for Pinterest discovery. Plus bonus story pin.
 */

export interface PinterestPin {
  id: string;
  board: string;
  title: string;
  description: string;
  altText: string;
  link: string;
  scheduledTime: string;
  hashtags: string[];
}

export const pinterestPins: PinterestPin[] = [
  {
    id: "pin-001",
    board: "AI Anime Art Inspiration",
    title: "Neon Ronin — Retro 90s Anime AI Art | Cyberpunk Samurai",
    description:
      "Epic retro 90s anime-style AI artwork of a lone samurai standing beneath neon-lit rain. Cel-shaded with Science SARU aesthetic, this cyberpunk piece features magenta fog, cherry blossom petals, and dramatic lens flare. Created with AniVerse AI. Get 10 free AI anime generations at AniVerse → aniverse-one-khaki.vercel.app\n\n#RetroAnime #CyberpunkArt #AISamurai #90sAnime #AniVerse #AIArt",
    altText:
      "Cel-shaded neon ronin samurai in crimson haori under magenta and cyan rain on a cyberpunk street, retro 90s OVA style",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-26T10:00:00+07:00",
    hashtags: ["RetroAnime", "CyberpunkArt", "AISamurai", "90sAnime"],
  },
  {
    id: "pin-002",
    board: "AI Anime Art Inspiration",
    title: "The Spirit Tree's Embrace — Ghibli-Inspired AI Art | Fantasy Landscape",
    description:
      "Breathtaking Studio Ghibli-inspired AI landscape featuring a colossal ancient tree with glowing blue leaves, Kodama spirits, and warm golden-hour light. Created with AniVerse AI using 'warm earth tones' and 'detailed foliage' prompts. Perfect for fantasy wallpaper and art inspiration. Create your own at aniverse-one-khaki.vercel.app\n\n#StudioGhibli #GhibliArt #FantasyLandscape #AIArt #AniVerse #DigitalPainting",
    altText:
      "Ancient tree with luminescent azure leaves on green hillside, kodama spirits peeking from roots, golden sunlight",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-26T10:00:00+07:00",
    hashtags: ["StudioGhibli", "GhibliArt", "FantasyLandscape", "AIArt"],
  },
  {
    id: "pin-003",
    board: "Anime Style Guide 2026",
    title: "Pixel Blade Samurai Zero — 16-Bit Pixel Art Anime | Retro Gaming",
    description:
      "Stunning fusion of 16-bit pixel art and modern anime design. A samurai warrior with neon sword in dynamic action pose against starry night sky. Features dithering techniques, limited palette, and 2.5D parallax background. Created with AniVerse AI. Try the pixel art style at aniverse-one-khaki.vercel.app\n\n#PixelArt #RetroGaming #AnimePixelArt #16Bit #AIArt #AniVerse #GameArt",
    altText:
      "16-bit pixel art samurai with glowing neon sword, retro RPG style with feudal Japan village background",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-26T10:00:00+07:00",
    hashtags: ["PixelArt", "RetroGaming", "AnimePixelArt", "16Bit"],
  },
  {
    id: "pin-004",
    board: "AI Anime Art Inspiration",
    title: "Frieren's Evening — Dusty Pastel Anime AI Art | Fantasy Romance",
    description:
      "Melancholic dusty pastel artwork inspired by Frieren's aesthetic. A lone mage with flowing white hair walks through wildflowers at sunset. Warm rose, amber, and cream palette with watercolor-like textures. Created with AniVerse AI — the trending Frieren style. Generate your own at aniverse-one-khaki.vercel.app\n\n#Frieren #DustyPastels #AnimeArt #AIArt #FantasyArt #AniVerse #MageArt",
    altText:
      "Lone mage with white hair and wide-brimmed hat walking through wildflower field at dusty rose sunset",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-26T10:00:00+07:00",
    hashtags: ["Frieren", "DustyPastels", "AnimeArt", "FantasyArt"],
  },
  {
    id: "pin-005",
    board: "AI Anime Art Inspiration",
    title: "Sakura Station — Watercolor Anime AI Art | Slice of Life",
    description:
      "Soft watercolor anime scene of a quiet train station in cherry blossom season. Pink petals drift across the platform as a lone figure waits beneath the station clock. Loose brushwork, visible paper grain, and pastel palette of blush pink, lavender, and powder blue. Ghibli-inspired everyday magic. Create at aniverse-one-khaki.vercel.app\n\n#WatercolorArt #CherryBlossom #SliceOfLife #AnimeBackground #AIArt #AniVerse",
    altText:
      "Rural train station in spring with cherry blossoms, pastel pink and lavender sky, watercolor style",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-26T10:00:00+07:00",
    hashtags: ["WatercolorArt", "CherryBlossom", "SliceOfLife", "AnimeBackground"],
  },
  {
    id: "pin-006",
    board: "Anime Style Guide 2026",
    title: "Chronicles of the Verdant Gate — Isekai Fantasy AI Art",
    description:
      "Epic isekai fantasy AI artwork showing a magical portal opening in an ancient forest. A teenager reaches toward a shimmering gate of vines and runes, revealing a floating continent beyond. Warm earth tones with emerald accents. Created with AniVerse AI. Start your isekai adventure at aniverse-one-khaki.vercel.app\n\n#Isekai #FantasyArt #PortalFantasy #AIArt #AniVerse #DigitalArt #AnimeFantasy",
    altText:
      "Magical vine portal opening in ancient forest, teenager stepping through to floating continent in sky",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-26T10:00:00+07:00",
    hashtags: ["Isekai", "FantasyArt", "PortalFantasy", "AnimeFantasy"],
  },
  {
    id: "pin-007",
    board: "AI Anime Art Inspiration",
    title: "Aurora Over Neo-Tokyo — Cyberpunk Cityscape AI Art",
    description:
      "Breathtaking cyberpunk cityscape at midnight with aurora borealis sweeping across the sky. Holographic billboards, flying vehicles, and neon-lit skyscrapers create an electric atmosphere. Rain-slicked surfaces reflect the neon chaos. Created with AniVerse AI. Generate cyberpunk art at aniverse-one-khaki.vercel.app\n\n#Cyberpunk #NeonArt #Cityscape #SciFiArt #AIArt #AniVerse #AuroraBorealis",
    altText:
      "Futuristic megacity at night with aurora borealis, holographic billboards, flying vehicles with light trails",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-26T10:00:00+07:00",
    hashtags: ["Cyberpunk", "NeonArt", "Cityscape", "SciFiArt"],
  },
  {
    id: "pin-008",
    board: "AI Anime Art Inspiration",
    title: "Lunar Festival Eve — Ghibli Festival Scene AI Art",
    description:
      "Magical Ghibli-inspired festival scene with two children in yukata running through lantern-lit streets. Paper lanterns in amber, crimson, and gold glow against indigo night. A giant paper moon floats above. Sparklers paint light trails through the air. Created with AniVerse AI. Create festival art at aniverse-one-khaki.vercel.app\n\n#GhibliArt #Festival #LanternFestival #AnimeScenery #AIArt #AniVerse #SummerMagic",
    altText:
      "Two children in yukata running through lantern-lit festival with sparklers, giant paper moon in night sky",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-26T10:00:00+07:00",
    hashtags: ["GhibliArt", "Festival", "LanternFestival", "AnimeScenery"],
  },
  {
    id: "pin-009",
    board: "Anime Style Guide 2026",
    title: "Gerbang di Antara Dua Dunia — Isekai Web Novel | AniVerse Story",
    description:
      "Dive into 'Gerbang di Antara Dua Dunia' (The Gate Between Two Worlds), an original isekai fantasy web novel from AniVerse. Follow Raka, a Yogyakarta art student who discovers his paintings are portals to a fantasy realm. Armed with the Brush of Destiny, he must save two worlds from eternal darkness. Read the full chapter FREE at aniverse-one-khaki.vercel.app\n\n#WebNovel #Isekai #FantasyStory #AniVerse #OriginalFiction #AnimeStory",
    altText:
      "AniVerse web novel story teaser — Gerbang di Antara Dua Dunia, fantasy isekai about a painter from Yogyakarta",
    link: "https://aniverse-one-khaki.vercel.app/data/stories",
    scheduledTime: "2026-07-26T10:30:00+07:00",
    hashtags: ["WebNovel", "Isekai", "FantasyStory", "AniVerse", "OriginalFiction"],
  },
];

export const boardMetadata = {
  primaryBoard: "AI Anime Art Inspiration",
  secondaryBoard: "Anime Style Guide 2026",
  date: "2026-07-26",
  totalPins: 9,
  ctaLink: "https://aniverse-one-khaki.vercel.app",
};
