/**
 * Pinterest Pin Descriptions — July 25, 2026
 *
 * Generated by Agent A7 (Social Media Empire)
 * Board: "AI Anime Art Inspiration" / "Anime Style Guide 2026"
 *
 * 7 pins — one per artwork, each with optimized SEO description
 * for Pinterest discovery.
 */

export interface PinterestPin {
  id: string;
  board: string;
  title: string;
  description: string;
  altText: string;
  link: string;
  scheduledTime: string;
  hashtags: string[];
}

export const pinterestPins: PinterestPin[] = [
  {
    id: "pin-001",
    board: "AI Anime Art Inspiration",
    title: "VHS Memories — Retro 90s Anime AI Art | Cel-Shaded Tokyo Nostalgia",
    description:
      "Epic retro 90s cel-shaded AI artwork of a teenage girl in a denim jacket listening to a Walkman on a Tokyo rooftop at sunset. Heavy cel-shading with thick black outlines, VHS scan lines, and chromatic aberration. Inspired by Science SARU's dynamic 1990s OVA aesthetic. Created with AniVerse AI. Get 10 free AI anime generations at AniVerse → aniverse-one-khaki.vercel.app\n\n#90sAnime #RetroAnime #VHSGrain #CelShaded #AniVerse #AIArt #Vaporwave",
    altText:
      "Cel-shaded teenage girl with Walkman on Tokyo rooftop at sunset, 90s retro VHS aesthetic with scan lines and chromatic aberration",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-25T10:00:00+07:00",
    hashtags: ["90sAnime", "RetroAnime", "VHSGrain", "CelShaded"],
  },
  {
    id: "pin-002",
    board: "Anime Style Guide 2026",
    title: "Futur Funk Dreamscape — Vaporwave Anime AI Art | Synthwave Dream",
    description:
      "Stunning vaporwave AI artwork featuring a neon Greek bust floating above a digital ocean, an anime girl in 90s streetwear on a pier, and retro Windows 95 UI elements. Synthwave sunset with horizontal scan lines. The TikTok-viral vaporwave anime aesthetic. Created with AniVerse AI. Try the vaporwave style at aniverse-one-khaki.vercel.app\n\n#Vaporwave #FutureFunk #SynthwaveArt #VaporwaveAesthetic #AniVerse #AIArt #DigitalDream",
    altText:
      "Vaporwave digital art with Greek bust neon, anime girl silhouette on pier, Windows 95 elements, synthwave sun over digital ocean",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-25T10:00:00+07:00",
    hashtags: ["Vaporwave", "FutureFunk", "SynthwaveArt", "VaporwaveAesthetic"],
  },
  {
    id: "pin-003",
    board: "AI Anime Art Inspiration",
    title: "The Last Campfire — Frieren-Inspired AI Art | Dusty Pastel Fantasy",
    description:
      "Melancholic Frieren-inspired AI artwork of four adventurers resting around a campfire under a star-dusted twilight sky. A white-haired elven mage in a wide-brimmed hat warms her hands. Muted dusty pastel palette — dusty rose, warm beige, sage green, faded lavender. Watercolor texture. Created with AniVerse AI. Generate Frieren-style art at aniverse-one-khaki.vercel.app\n\n#Frieren #DustyPastels #FantasyArt #Campfire #AIArt #AniVerse #ElvenMage",
    altText:
      "Four adventurers around campfire under starry sky, white-haired elven mage in wide hat warming hands, dusty pastel colors, watercolor texture",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-25T10:00:00+07:00",
    hashtags: ["Frieren", "DustyPastels", "FantasyArt", "Campfire"],
  },
  {
    id: "pin-004",
    board: "AI Anime Art Inspiration",
    title: "Mucha's Celestial Maiden — Art Nouveau Anime AI Art | Alphonse Mucha Style",
    description:
      "Exquisite Art Nouveau × anime fusion inspired by Alphonse Mucha. An ethereal anime maiden with emerald hair woven with flowering vines, stained-glass halo in jewel tones, peacock feathers, and lotus motifs. Warm gold, teal, and ruby palette. Premium art print aesthetic. Created with AniVerse AI. Create Mucha-style art at aniverse-one-khaki.vercel.app\n\n#ArtNouveau #Mucha #MuchaStyle #AnimeArtNouveau #AniVerse #AIArt #BelleEpoque",
    altText:
      "Art Nouveau anime maiden with flowing emerald hair, stained glass halo, peacock feathers, Mucha-inspired decorative borders",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-25T10:00:00+07:00",
    hashtags: ["ArtNouveau", "Mucha", "MuchaStyle", "AnimeArtNouveau"],
  },
  {
    id: "pin-005",
    board: "AI Anime Art Inspiration",
    title: "Grandmother's Photo Album — Sepia Nostalgia AI Art | 1970s Japan Romance",
    description:
      "Heartwarming sepia-toned AI artwork of a young couple on a park bench in 1970s Japan. Film grain texture, light leaks, and dust spots give it the authentic feel of a vintage photograph. A boy in retro school uniform and a girl in traditional shifuku sharing a shy moment under cherry blossoms. Hand-written date: Showa 48.4.15. Created with AniVerse AI.\n\n#Sepia #Nostalgia #1970sJapan #VintagePhotography #AniVerse #AIArt #CherryBlossom",
    altText:
      "Sepia-toned young couple on park bench in 1970s Japan, boy in school uniform, girl in shifuku, cherry blossoms falling, vintage photo style",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-25T10:00:00+07:00",
    hashtags: ["Sepia", "Nostalgia", "1970sJapan", "VintagePhotography"],
  },
  {
    id: "pin-006",
    board: "Anime Style Guide 2026",
    title: "Witch of the Violet Hour — Pastel Goth AI Art | Cozy Occult Anime",
    description:
      "Enchanting pastel goth AI artwork featuring a young witch with charcoal-black hair and purple highlights on a wrought-iron balcony. Oversized knit sweater, pleated skirt, combat boots, and a black cat curled in her lap. Glowing violet magical symbols float around her fingers as twilight settles over a foggy city. Muted purple and charcoal palette with dusty pink accents. Created with AniVerse AI.\n\n#PastelGoth #Witchy #CozyOccult #GothArt #AniVerse #AIArt #DarkAcademia",
    altText:
      "Pastel goth witch on balcony with black cat, charcoal hair with purple highlights, glowing arcane symbols, foggy twilight city",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-25T10:00:00+07:00",
    hashtags: ["PastelGoth", "Witchy", "CozyOccult", "GothArt"],
  },
  {
    id: "pin-007",
    board: "AI Anime Art Inspiration",
    title: "Guardian of the Ancient Wood — Ghibli-Inspired AI Art | Forest Spirit",
    description:
      "Breathtaking Ghibli-inspired AI artwork of a colossal forest spirit wolf made of moss, emerald foliage, and blooming flowers guarding an ancient shrine. Golden sunlight streams through towering cedars, Kodama spirits peek from tree hollows, and firefly wisps float through the air. Rich warm earth tones and vibrant emerald greens. Studio Ghibli's majestic nature aesthetic. Created with AniVerse AI.\n\n#GhibliArt #StudioGhibli #ForestSpirit #FantasyLandscape #AniVerse #AIArt #Kodama",
    altText:
      "Colossal wolf forest spirit made of moss and flowers guarding ancient shrine, golden sunlight through cedar trees, kodama spirits, Ghibli style",
    link: "https://aniverse-one-khaki.vercel.app/dashboard/gallery",
    scheduledTime: "2026-07-25T10:00:00+07:00",
    hashtags: ["GhibliArt", "StudioGhibli", "ForestSpirit", "FantasyLandscape"],
  },
];

export const boardMetadata = {
  primaryBoard: "AI Anime Art Inspiration",
  secondaryBoard: "Anime Style Guide 2026",
  date: "2026-07-25",
  totalPins: 7,
  ctaLink: "https://aniverse-one-khaki.vercel.app",
};
