/**
 * TikTok Short Video Scripts — July 27, 2026
 *
 * Generated by Agent A7 (Social Media Empire)
 * Format: 60-second time-lapse / showcase video
 * Style: Fast-paced, trending audio, visual focus
 *
 * Three video variants optimized for TikTok's algorithm:
 *   A) "8 Artworks in 60 Seconds" — fast showcase
 *   B) "Photo-to-Anime Transformation" — AI generation process
 *   C) "Ghibli vs Cyberpunk" — style comparison challenge
 */

export interface TikTokScript {
  id: string;
  variant: "A" | "B" | "C";
  title: string;
  duration: number; // seconds
  audioSuggestion: string;
  scenes: TikTokScene[];
  caption: string;
  hashtags: string[];
  scheduledTime: string;
}

export interface TikTokScene {
  time: string; // timestamp e.g. "0:00"
  visual: string;
  textOverlay: string;
  voiceover: string;
  transition: string;
}

export const tiktokVariantA: TikTokScript = {
  id: "tt-a-20260727",
  variant: "A",
  title: "8 AI Anime Artworks in 60 Seconds 🔥 Monday Drop",
  duration: 60,
  audioSuggestion: "Upbeat synthwave remix / Monday motivation beat — trending anime edit audio 2026",
  scenes: [
    {
      time: "0:00",
      visual: "Ronin of the Neon Rain full artwork — rain particle overlay, slow zoom on ronin's face",
      textOverlay: "MONDAY ART DROP 🔥",
      voiceover: "Welcome to AniVerse — 8 new AI anime masterpieces dropping right now.",
      transition: "Rain splash reveal",
    },
    {
      time: "0:07",
      visual: "The Spirit Weaver's Grove — bioluminescent glow pulse effect, mushroom zoom in",
      textOverlay: "GHIBLI MAGIC 🍄",
      voiceover: "Ghibli-inspired bioluminescent forest with a spirit weaver at its heart.",
      transition: "Soft glow crossfade",
    },
    {
      time: "0:14",
      visual: "Photo-to-Anime Street Style Portrait — sparkle effect on eyes, color pop animation",
      textOverlay: "PHOTO-TO-ANIME 📸",
      voiceover: "The viral photo-to-anime trend — turn any photo into Harajuku anime magic.",
      transition: "Sparkle burst",
    },
    {
      time: "0:21",
      visual: "Celestial Duel at Dusk — impact frame freeze with speed lines, slow replay",
      textOverlay: "90S CEL-SHADED 💥",
      voiceover: "Retro 90s cel-shaded battle — lightning vs fire, pure OVA nostalgia.",
      transition: "Impact frame glitch",
    },
    {
      time: "0:28",
      visual: "Neon Dreams: Vaporwave Station — CRT scan line overlay, neon flicker effect",
      textOverlay: "VAPORWAVE 🌅",
      voiceover: "Vaporwave station frozen in time — outrun aesthetic at its finest.",
      transition: "CRT screen wipe",
    },
    {
      time: "0:35",
      visual: "Paper Lantern Festival — float animation on lanterns, warm glow bloom",
      textOverlay: "WATERCOLOR 🏮",
      voiceover: "Watercolor lantern festival — summer romance captured in soft pastels.",
      transition: "Warm glow dissolve",
    },
    {
      time: "0:42",
      visual: "Aethel: The Chronomancer's Apprentice — clock gear rotation overlay, golden thread particles",
      textOverlay: "FANTASY CHARACTER ✨",
      voiceover: "Fantasy character design — a chronomancer wielding the threads of time itself.",
      transition: "Clock spiral wipe",
    },
    {
      time: "0:50",
      visual: "Sakura Storm Over Cyber-Tokyo — holographic petal particle storm, glitch effect on skyscraper",
      textOverlay: "BIO-CYBERPUNK 🌸",
      voiceover: "Bio-cyberpunk sakura — where nature reclaims the neon megacity.",
      transition: "Petal storm reveal",
    },
    {
      time: "0:57",
      visual: "Split screen of all 8 artworks in grid → AniVerse logo + phone mockup",
      textOverlay: "CREATE YOURS FREE → LINK IN BIO",
      voiceover: "Which one's your favorite? Get 10 free generations at AniVerse!",
      transition: "Grid collapse to CTA",
    },
  ],
  caption:
    "8 AI anime artworks dropping this Monday 🔥 Which one hits different? 1. Cyberpunk Ronin 2. Ghibli Forest 3. Photo-to-Anime 4. 90s Battle 5. Vaporwave 6. Watercolor Festival 7. Chronomancer 8. Bio-Cyberpunk Sakura\n\nCreate your own FREE at AniVerse 🎨 Link in bio!\n\n#animeart #aianime #aniverse #digitalart #animeedit #fyp #arttiktok #mondaymotivation",
  hashtags: [
    "animeart",
    "aianime",
    "aniverse",
    "digitalart",
    "animeedit",
    "fyp",
    "arttiktok",
    "animetok",
    "aiartwork",
    "animecommunity",
    "animefyp",
    "viralart",
    "artstyle",
    "animeshowcase",
    "aigenerated",
    "cyberpunk",
    "ghibli",
    "vaporwave",
    "mondaymotivation",
  ],
  scheduledTime: "2026-07-27T11:00:00+07:00",
};

export const tiktokVariantB: TikTokScript = {
  id: "tt-b-20260727",
  variant: "B",
  title: "Photo to Anime HARAJUKU Style 🤯 | AI Transformation Magic",
  duration: 45,
  audioSuggestion:
    "Chill lofi beat → beat drop at reveal moment — trending 'art reveal' sound 2026",
  scenes: [
    {
      time: "0:00",
      visual: "Close-up on AniVerse prompt input field typing: 'Harajuku street fashion, photo-to-anime, sparkle eyes, twin tails, Shibuya bokeh'",
      textOverlay: "STEP 1: UPLOAD YOUR PHOTO 📱",
      voiceover: "Start with a photo of yourself. Any pose, any style.",
      transition: "None",
    },
    {
      time: "0:07",
      visual: "Before photo (real person) → AniVerse loading → After reveal animation",
      textOverlay: "STEP 2: AI TRANSFORMS YOU ⚡",
      voiceover: "AniVerse's AI analyzes your features and reimagines you as anime.",
      transition: "Sparkle burst",
    },
    {
      time: "0:15",
      visual: "Photo-to-Anime Street Style Portrait reveals — dramatic full reveal with particle effects",
      textOverlay: "RESULT: HARAJUKU ANIME YOU ✨",
      voiceover: "Look at this! Harajuku anime you — complete with sparkle eyes and turquoise twin tails!",
      transition: "Whoosh reveal with glow",
    },
    {
      time: "0:25",
      visual: "Split screen: 3 different photo-to-anime examples cycling (street style, casual, formal)",
      textOverlay: "ANY PHOTO → ANIME MAGIC 🌟",
      voiceover: "Whether street style, casual, or formal — every photo becomes anime perfection.",
      transition: "Triple split",
    },
    {
      time: "0:35",
      visual: "AniVerse interface with photo upload feature → CTA screen",
      textOverlay: "TRY IT FREE → ANIVERSE.APP",
      voiceover: "Turn YOUR photos into anime FREE at AniVerse. Link in bio!",
      transition: "Zoom to CTA",
    },
  ],
  caption:
    "Turn yourself into a Harajuku anime character 🤯 Photo-to-anime AI that actually looks THIS good! Try it FREE at AniVerse 🎨 Link in bio!\n\n#phototoanime #aianime #animetransformation #harajuku #aniverse #satisfying #fyp #aichallenge",
  hashtags: [
    "phototoanime",
    "aianime",
    "animetransformation",
    "harajuku",
    "aniverse",
    "satisfying",
    "fyp",
    "aiartprocess",
    "artreveal",
    "aigenerated",
    "animeportrait",
    "satisfyingvideo",
    "aifilter",
    "animetrend",
  ],
  scheduledTime: "2026-07-27T14:00:00+07:00",
};

export const tiktokVariantC: TikTokScript = {
  id: "tt-c-20260727",
  variant: "C",
  title: "Ghibli vs Cyberpunk 🍄⚔️ | Which Anime Style Wins?",
  duration: 35,
  audioSuggestion:
    "Beat switch from soft orchestral to heavy synth/bass — trending style comparison audio",
  scenes: [
    {
      time: "0:00",
      visual: "Split screen: The Spirit Weaver's Grove (left) vs Ronin of the Neon Rain (right)",
      textOverlay: "GHIBLI VS CYBERPUNK 🔄",
      voiceover:
        "Two worlds. Two moods. One impossible choice. Ghibli magic or cyberpunk grit?",
      transition: "Vertical split slide in",
    },
    {
      time: "0:05",
      visual: "Zoom into The Spirit Weaver's Grove — mushrooms glowing, will-o'-wisps dancing",
      textOverlay: "GHIBLI: PEACE & WONDER 🍄",
      voiceover: "Ghibli brings you enchanted forests, bioluminescent magic, and pure wonder.",
      transition: "Soft glow expand",
    },
    {
      time: "0:12",
      visual: "Zoom into Ronin of the Neon Rain — neon reflections, rain on straw hat",
      textOverlay: "CYBERPUNK: EDGE & STYLE ⚔️",
      voiceover: "Cyberpunk gives you neon rain, stoic ronins, and high-contrast drama.",
      transition: "Rain splash glitch",
    },
    {
      time: "0:19",
      visual: "Quick montage: Paper Lantern Festival (left), Sakura Storm Cybertokyo (right)",
      textOverlay: "SOFT vs HARSH 🌸⚡",
      voiceover: "Soft watercolor festivals vs bio-cyberpunk sakura storms — which vibe are you?",
      transition: "Fast cross dissolve",
    },
    {
      time: "0:26",
      visual: "AniVerse UI with style selector showing Ghibli and Cyberpunk presets → CTA",
      textOverlay: "YOU DON'T HAVE TO CHOOSE 🏆",
      voiceover: "Good news — you don't have to choose! Get BOTH styles FREE at AniVerse!",
      transition: "Morph to AniVerse logo",
    },
  ],
  caption:
    "Ghibli vs Cyberpunk — which anime style wins? 🍄⚔️ Vote in the comments! 1️⃣ Ghibli Magic 2️⃣ Cyberpunk Edge\n\nGet both styles FREE at AniVerse 🎨 Link in bio!\n\n#ghiblivscyberpunk #animeart #stylechallenge #aniverse #aianime #fyp #artstyle #ghibli #cyberpunk",
  hashtags: [
    "ghiblivscyberpunk",
    "animeart",
    "stylechallenge",
    "aniverse",
    "aianime",
    "fyp",
    "artstyle",
    "animeedit",
    "comparison",
    "ghibli",
    "cyberpunk",
    "aesthetic",
    "animeaesthetic",
  ],
  scheduledTime: "2026-07-27T17:00:00+07:00",
};

export const tiktokMetadata = {
  date: "2026-07-27",
  variants: 3,
  totalDuration: "35–60 seconds each",
  postingCadence: "Every 3 hours (11:00 / 14:00 / 17:00 WIB)",
  primaryHashtags: ["aniverse", "aianime", "animeart", "fyp"],
  ctaLink: "https://aniverse-one-khaki.vercel.app",
};
