/**
 * TikTok Short Video Scripts — July 25, 2026
 *
 * Generated by Agent A7 (Social Media Empire)
 * Format: 60-second time-lapse / showcase video
 * Style: Fast-paced, trending audio, visual focus
 *
 * Three video variants optimized for TikTok's algorithm:
 *   A) "7 Artworks in 60 Seconds" — fast showcase
 *   B) "From Prompt to Artwork" — AI generation process
 *   C) "Style Challenge: 90s vs Modern" — compare retro and modern styles
 */

export interface TikTokScript {
  id: string;
  variant: "A" | "B" | "C";
  title: string;
  duration: number; // seconds
  audioSuggestion: string;
  scenes: TikTokScene[];
  caption: string;
  hashtags: string[];
  scheduledTime: string;
}

export interface TikTokScene {
  time: string; // timestamp e.g. "0:00"
  visual: string;
  textOverlay: string;
  voiceover: string;
  transition: string;
}

export const tiktokVariantA: TikTokScript = {
  id: "tt-a-20260725",
  variant: "A",
  title: "7 AI Anime Artworks in 60 Seconds 🔥",
  duration: 60,
  audioSuggestion: "Upbeat phonk remix / lo-fi beat switch — trending anime edit audio 2026",
  scenes: [
    {
      time: "0:00",
      visual: "VHS Memories full artwork — VHS scan line overlay animation, slow zoom in",
      textOverlay: "7 AI ANIME ARTWORKS 🔥",
      voiceover: "Welcome to AniVerse — where AI creates anime magic.",
      transition: "VHS static reveal",
    },
    {
      time: "0:07",
      visual: "Futur Funk Dreamscape — grid lines overlay, neon pulse effect",
      textOverlay: "VAPORWAVE 🌊",
      voiceover: "Today we generated 7 pieces across the hottest anime styles of 2026.",
      transition: "Grid wipe",
    },
    {
      time: "0:14",
      visual: "The Last Campfire — campfire embers particle effect, slow pan across party",
      textOverlay: "FRIEREN PASTELS 🔥",
      voiceover: "From Frieren-style dusty pastels to 90s VHS nostalgia.",
      transition: "Cross dissolve",
    },
    {
      time: "0:21",
      visual: "Mucha's Celestial Maiden — decorative border zoom in, gold shimmer effect",
      textOverlay: "ART NOUVEAU ✨",
      voiceover: "Art Nouveau x Anime is the rising niche you NEED to try.",
      transition: "Ornate frame wipe",
    },
    {
      time: "0:28",
      visual: "Grandmother's Photo Album — film grain overlay, vignette darken",
      textOverlay: "SEPIA NOSTALGIA 📷",
      voiceover: "Sepia nostalgia — vintage 1970s Japan vibes that hit different.",
      transition: "Film reel skip",
    },
    {
      time: "0:35",
      visual: "Witch of the Violet Hour — magical symbol glow animation, purple fog",
      textOverlay: "PASTEL GOTH 🌙",
      voiceover: "Pastel goth is the emerging alternative aesthetic blowing up.",
      transition: "Glitch to purple",
    },
    {
      time: "0:42",
      visual: "Guardian of the Ancient Wood — slow upward pan through trees to reveal wolf spirit",
      textOverlay: "GHIBLI MAGIC 🐺",
      voiceover: "And Ghibli-inspired forest spirits — always an absolute masterpiece.",
      transition: "Golden light burst",
    },
    {
      time: "0:50",
      visual: "Split screen of all 7 artworks in grid → AniVerse logo + phone mockup",
      textOverlay: "CREATE YOURS FREE → LINK IN BIO",
      voiceover: "Which one's your favorite? Comment below! Get 10 free gens at AniVerse!",
      transition: "Grid collapse to CTA",
    },
  ],
  caption:
    "7 AI anime artworks in 60 seconds 🔥 Which style hits different? 1. 90s VHS 2. Vaporwave 3. Frieren Pastel 4. Art Nouveau 5. Sepia Nostalgia 6. Pastel Goth 7. Ghibli Spirit\n\nCreate your own FREE at AniVerse 🎨 Link in bio!\n\n#animeart #aianime #aniverse #digitalart #animeedit #fyp #arttiktok",
  hashtags: [
    "animeart",
    "aianime",
    "aniverse",
    "digitalart",
    "animeedit",
    "fyp",
    "arttiktok",
    "animetok",
    "aiartwork",
    "animecommunity",
    "animefyp",
    "viralart",
    "artstyle",
    "animeshowcase",
    "aigenerated",
    "vaporwave",
    "pastelgoth",
    "ghibli",
  ],
  scheduledTime: "2026-07-25T11:00:00+07:00",
};

export const tiktokVariantB: TikTokScript = {
  id: "tt-b-20260725",
  variant: "B",
  title: "From Prompt to Vaporwave Anime 🤯 | AI Generation Magic",
  duration: 45,
  audioSuggestion:
    "Chill lofi beat → beat drop at reveal moment — trending 'art reveal' sound",
  scenes: [
    {
      time: "0:00",
      visual: "Close-up on AniVerse prompt input field typing: 'Vaporwave anime girl, Greek bust neon, synthwave sunset'",
      textOverlay: "STEP 1: WRITE YOUR VISION 📝",
      voiceover: "Start with a dream. We wanted vaporwave surrealism meets anime.",
      transition: "None",
    },
    {
      time: "0:08",
      visual: "AniVerse loading animation — progress bar, particle effects",
      textOverlay: "STEP 2: AI DREAMS IT ⏳",
      voiceover: "AniVerse's AI processes your vision in seconds.",
      transition: "Fade through white",
    },
    {
      time: "0:18",
      visual: "Futur Funk Dreamscape reveals — dramatic zoom out from center",
      textOverlay: "RESULT: FUTUR FUNK DREAMSCAPE ⚡",
      voiceover: "And here it is — pure vaporwave anime magic in 4K.",
      transition: "Whoosh reveal with glow",
    },
    {
      time: "0:28",
      visual: "Split screen: 3 prompt texts vs 3 final artworks (VHS Memories, The Last Campfire, Guardian)",
      textOverlay: "3 PROMPTS → 3 WORLDS 🌍",
      voiceover: "From '90s Tokyo rooftop' to 'Frieren campfire' to 'Ghibli forest spirit' — endless possibilities.",
      transition: "Triple split",
    },
    {
      time: "0:38",
      visual: "AniVerse interface with style selector showcasing 7 presets → CTA screen",
      textOverlay: "TRY IT FREE → ANIVERSE.APP",
      voiceover: "10 free generations waiting. Your masterpiece is one prompt away!",
      transition: "Zoom to CTA",
    },
  ],
  caption:
    "Watch AI turn words into vaporwave anime dreams 🤯 From prompt to masterpiece in seconds. Try AniVerse FREE — link in bio! 🎨\n\n#aigenerated #animeart #prompttoart #satisfying #aniverse #creativeai #fyp #vaporwave",
  hashtags: [
    "aigenerated",
    "animeart",
    "prompttoart",
    "satisfying",
    "aniverse",
    "creativeai",
    "fyp",
    "aiartprocess",
    "artreveal",
    "aianime",
    "vaporwave",
    "satisfyingvideo",
  ],
  scheduledTime: "2026-07-25T14:00:00+07:00",
};

export const tiktokVariantC: TikTokScript = {
  id: "tt-c-20260725",
  variant: "C",
  title: "90s Anime vs 2026 AI Anime 🔄 | Then vs Now Challenge",
  duration: 35,
  audioSuggestion:
    "Beat switch from retro 8-bit to modern phonk — trending comparison audio",
  scenes: [
    {
      time: "0:00",
      visual: "Split screen: left side 'VHS Memories', right side same but with live action filter overlay",
      textOverlay: "90s ANIME VS AI 2026 🔄",
      voiceover:
        "Remember 90s OVAs? Here's what happens when AI remixes that aesthetic for 2026.",
      transition: "None",
    },
    {
      time: "0:05",
      visual: "VHS Memories — zoom in on Walkman, cassette tape visual effect",
      textOverlay: "1995 VIBES 📼",
      voiceover: "The 90s cel-shaded look with thick outlines and neon pops.",
      transition: "VHS tracking lines",
    },
    {
      time: "0:12",
      visual: "Futur Funk Dreamscape — grid lines overlay, digital glitch effect",
      textOverlay: "2026 AI UPGRADE ⚡",
      voiceover: "Now AI remixes it with vaporwave surrealism and 4K detail.",
      transition: "Digital glitch",
    },
    {
      time: "0:19",
      visual: "Split comparison: Grandmother's Photo Album (left) vs modern digital painting style (right)",
      textOverlay: "SEPIA vs DIGITAL 🎨",
      voiceover: "Same nostalgic heart, but with AI-powered precision and texture.",
      transition: "Vertical split slide",
    },
    {
      time: "0:26",
      visual: "Guardian of the Ancient Wood — single frame, majestic zoom out",
      textOverlay: "THEN vs NOW: YOU DECIDE 🏆",
      voiceover: "Which era wins? Try both styles FREE at AniVerse — link in bio!",
      transition: "Morph to AniVerse logo",
    },
  ],
  caption:
    "90s anime vibes vs 2026 AI remix 🔄 Which era did it better? 1️⃣ Retro 90s 2️⃣ AI Remix\n\nCreate your own style fusion FREE at AniVerse 🎨 Link in bio!\n\n#90svs2026 #animeart #aichallenge #thenvsnow #aniverse #aianime #fyp #retroanime",
  hashtags: [
    "90svs2026",
    "animeart",
    "aichallenge",
    "thenvsnow",
    "aniverse",
    "aianime",
    "fyp",
    "artstyle",
    "animeedit",
    "comparison",
    "90sanime",
    "retroanime",
  ],
  scheduledTime: "2026-07-25T17:00:00+07:00",
};

export const tiktokMetadata = {
  date: "2026-07-25",
  variants: 3,
  totalDuration: "35–60 seconds each",
  postingCadence: "Every 3 hours (11:00 / 14:00 / 17:00 WIB)",
  primaryHashtags: ["aniverse", "aianime", "animeart", "fyp"],
  ctaLink: "https://aniverse-one-khaki.vercel.app",
};
