/**
 * TikTok Short Video Scripts — July 28, 2026
 *
 * Generated by Agent A7 (Social Media Empire)
 * Format: 45-60 second showcase / transformation videos
 * Style: Fast-paced, trending audio, visual focus
 *
 * Three video variants optimized for TikTok's algorithm:
 *   A) "7 Artworks in 60 Seconds" — fast showcase
 *   B) "Pastel Goth Transformation" — AI generation process
 *   C) "Ghibli vs Cyberpunk vs Pastel Goth" — style comparison
 */

export interface TikTokScript {
  id: string;
  variant: "A" | "B" | "C";
  title: string;
  duration: number; // seconds
  audioSuggestion: string;
  scenes: TikTokScene[];
  caption: string;
  hashtags: string[];
  scheduledTime: string;
}

export interface TikTokScene {
  time: string; // timestamp e.g. "0:00"
  visual: string;
  textOverlay: string;
  voiceover: string;
  transition: string;
}

export const tiktokVariantA: TikTokScript = {
  id: "tt-a-20260728",
  variant: "A",
  title: "7 AI Anime Artworks in 60 Seconds 🔥 Tuesday Drop",
  duration: 60,
  audioSuggestion: "Upbeat synthwave remix / Tuesday motivation beat — trending anime edit audio 2026",
  scenes: [
    {
      time: "0:00",
      visual: "The Sky Fisher's Last Catch full artwork — slow zoom on fisherman casting line, star particles floating",
      textOverlay: "TUESDAY ART DROP 🌠",
      voiceover: "Welcome to AniVerse — 7 new AI anime masterpieces dropping right now.",
      transition: "Star sparkle reveal",
    },
    {
      time: "0:08",
      visual: "Crimson Duel in the Bamboo Grove — impact frame freeze with bamboo splinter particles, slow replay",
      textOverlay: "HIGH-CONTRAST BATTLE ⚔️",
      voiceover: "High-contrast samurai duel — fire vs lightning, Jujutsu Kaisen style.",
      transition: "Impact frame glitch",
    },
    {
      time: "0:16",
      visual: "Neon Shinobi, Third Shift — rain particle overlay, circuit trace animation on mechanical arm, neon flicker",
      textOverlay: "CYBERPUNK NINJA 🌃",
      voiceover: "Cyber-enhanced shinobi watching over a rain-slicked megacity at night.",
      transition: "Rain splash reveal",
    },
    {
      time: "0:24",
      visual: "Galactic Battle High: After School — nebula rotation effect, speed lines radiating from students, energy glow",
      textOverlay: "90S SCI-FI 🚀",
      voiceover: "Retro 90s cel-shaded — three students on a starship roof above a nebula!",
      transition: "Whoosh wipe",
    },
    {
      time: "0:32",
      visual: "The Witch's Dusty Garden — soft glow pulse on fungi, black rose slow bloom, crow wing flap overlay",
      textOverlay: "PASTEL GOTH 🌙",
      voiceover: "Pastel gothic witch tending her moonlit garden of black roses and glowing fungi.",
      transition: "Soft dissolve",
    },
    {
      time: "0:40",
      visual: "The Red String of Fate — crimson thread glow animation, greyscale to color reveal on string only",
      textOverlay: "MONOCHROME + RED 🔴",
      voiceover: "Monochrome portrait with a single crimson thread — fate, destiny, and minimalism.",
      transition: "Color accent pop",
    },
    {
      time: "0:48",
      visual: "The Abyss Blooms With Light — crystal pulse light animation, moth wing flap, spore particle fall",
      textOverlay: "BIOLUMINESCENT 💎",
      voiceover: "Bioluminescent crystal cavern — Princess Mononoke meets Avatar with a cyber soul.",
      transition: "Crystal shimmer wipe",
    },
    {
      time: "0:56",
      visual: "Split screen grid of all 7 artworks → AniVerse logo + phone mockup",
      textOverlay: "CREATE YOURS FREE → LINK IN BIO",
      voiceover: "Which one's your favorite? Get 10 free generations at AniVerse!",
      transition: "Grid collapse to CTA",
    },
  ],
  caption:
    "7 AI anime artworks dropping this Tuesday 🌠 Which one hits different? 1. Ghibli Fisherman 2. Samurai Duel 3. Cyber Ninja 4. 90s Sci-Fi 5. Pastel Goth Witch 6. Red String Fate 7. Crystal Abyss\n\nCreate your own FREE at AniVerse 🎨 Link in bio!\n\n#animeart #aianime #aniverse #digitalart #animeedit #fyp #arttiktok #tuesdayvibes",
  hashtags: [
    "animeart",
    "aianime",
    "aniverse",
    "digitalart",
    "animeedit",
    "fyp",
    "arttiktok",
    "animetok",
    "aiartwork",
    "animecommunity",
    "animefyp",
    "viralart",
    "artstyle",
    "animeshowcase",
    "aigenerated",
    "ghibli",
    "cyberpunk",
    "pastelgoth",
    "tuesdayvibes",
  ],
  scheduledTime: "2026-07-28T11:00:00+07:00",
};

export const tiktokVariantB: TikTokScript = {
  id: "tt-b-20260728",
  variant: "B",
  title: "Pastel Goth Witch Transformation 🌙✨ | AI Art Process Video",
  duration: 45,
  audioSuggestion:
    "Soft ethereal lofi → beat switch to dark melodic — trending 'dark aesthetic' sound 2026",
  scenes: [
    {
      time: "0:00",
      visual: "Close-up on AniVerse prompt input field typing: 'silver-haired witch, dusty lavender dress, moonlit garden, black roses, pastel goth, bioluminescent fungi, melancholy beauty'",
      textOverlay: "STEP 1: WRITE YOUR VISION 📝",
      voiceover: "Start with a prompt. Paint the scene with words — a witch, a moonlit garden, black roses.",
      transition: "None",
    },
    {
      time: "0:07",
      visual: "AniVerse style selector highlighting 'Pastel Goth / Dusty Pastels' preset → loading animation",
      textOverlay: "STEP 2: PICK PASTEL GOTH 🎨",
      voiceover: "Select the Pastel Goth style preset — dusty lavenders, charcoal shadows, soft bioluminescence.",
      transition: "Soft fade",
    },
    {
      time: "0:15",
      visual: "Loading → The Witch's Dusty Garden reveals with dramatic slow zoom, glow particle burst",
      textOverlay: "RESULT: MOONLIT WITCH ✨",
      voiceover: "And here she is — a silver-haired witch in her dusty garden, where even darkness wears soft colors.",
      transition: "Glow burst reveal",
    },
    {
      time: "0:25",
      visual: "Detail zoom: black roses → luminescent fungi → crow with white eye → lace trim on dress",
      textOverlay: "EVERY DETAIL MATTERS 🔍",
      voiceover: "Look at the detail — black roses, glowing fungi, a crow with one white eye, dark lace trim.",
      transition: "Slow zoom",
    },
    {
      time: "0:35",
      visual: "AniVerse interface showing Pastel Goth preset + gallery of similar styles → CTA screen",
      textOverlay: "CREATE YOUR OWN → ANIVERSE.APP",
      voiceover: "Want your own dark fantasy masterpiece? Create FREE at AniVerse! Link in bio!",
      transition: "Zoom to CTA",
    },
  ],
  caption:
    "Watch a pastel goth witch come to life 🌙✨ This AI-generated masterpiece took seconds to create. Imagine YOUR dark fantasy vision — try it FREE at AniVerse 🎨\n\n#pastelgoth #witchtok #aianime #aniverse #satisfying #fyp #aiartprocess #darkfantasy",
  hashtags: [
    "pastelgoth",
    "witchtok",
    "aianime",
    "aniverse",
    "satisfying",
    "fyp",
    "aiartprocess",
    "artreveal",
    "darkfantasy",
    "aigenerated",
    "animeportrait",
    "satisfyingvideo",
    "aifilter",
    "animetrend",
    "witchaesthetic",
  ],
  scheduledTime: "2026-07-28T14:00:00+07:00",
};

export const tiktokVariantC: TikTokScript = {
  id: "tt-c-20260728",
  variant: "C",
  title: "Ghibli vs Cyberpunk vs Pastel Goth 🍄🌃🌙 | Which Style Wins?",
  duration: 40,
  audioSuggestion:
    "Triple beat switch: gentle orchestral → heavy synth → dark ethereal — trending style battle audio",
  scenes: [
    {
      time: "0:00",
      visual: "Triple split screen: Sky Fisher's Last Catch (left), Neon Shinobi (center), Witch's Dusty Garden (right)",
      textOverlay: "GHIBLI vs CYBERPUNK vs PASTEL GOTH 🔄",
      voiceover:
        "Three worlds. Three moods. One impossible choice. Ghibli serenity, cyberpunk edge, or pastel goth melancholy?",
      transition: "Triple split slide in",
    },
    {
      time: "0:06",
      visual: "Zoom into The Sky Fisher's Last Catch — dandelion puffs floating, star sea shimmer, kodama spirits",
      textOverlay: "GHIBLI: PEACE & WONDER 🌠",
      voiceover: "Ghibli offers you starry skies, dandelion boats, and the quiet magic of dawn.",
      transition: "Soft float expand",
    },
    {
      time: "0:14",
      visual: "Zoom into Neon Shinobi — rain on neon sign, circuit traces glowing, cityscape below",
      textOverlay: "CYBERPUNK: EDGE & STYLE 🌃",
      voiceover: "Cyberpunk gives you neon rain, cybernetic eyes, and the solitude of the urban hunter.",
      transition: "Rain splash glitch",
    },
    {
      time: "0:22",
      visual: "Zoom into The Witch's Dusty Garden — black roses, fungi glow, crow watching",
      textOverlay: "PASTEL GOTH: MYSTERY & GRACE 🌙",
      voiceover: "Pastel goth brings moonlit gardens, dusty lavender, and beauty in twilight.",
      transition: "Soft dark dissolve",
    },
    {
      time: "0:30",
      visual: "AniVerse UI with style selector showing Ghibli, Cyberpunk, and Pastel Goth presets → CTA",
      textOverlay: "YOU DON'T HAVE TO CHOOSE 🏆",
      voiceover: "Best part — you don't have to choose! Get ALL THREE styles FREE at AniVerse!",
      transition: "Morph to AniVerse logo",
    },
  ],
  caption:
    "Ghibli vs Cyberpunk vs Pastel Goth — which anime style wins? 🍄🌃🌙 Vote in the comments! 1️⃣ Ghibli Magic 2️⃣ Cyberpunk Edge 3️⃣ Pastel Goth Mystery\n\nGet ALL styles FREE at AniVerse 🎨 Link in bio!\n\n#ghiblivscyberpunk #animeart #stylechallenge #aniverse #aianime #fyp #artstyle #pastelgoth #ghibli #cyberpunk",
  hashtags: [
    "ghiblivscyberpunk",
    "animeart",
    "stylechallenge",
    "aniverse",
    "aianime",
    "fyp",
    "artstyle",
    "animeedit",
    "comparison",
    "ghibli",
    "cyberpunk",
    "pastelgoth",
    "aesthetic",
    "animeaesthetic",
  ],
  scheduledTime: "2026-07-28T17:00:00+07:00",
};

export const tiktokMetadata = {
  date: "2026-07-28",
  variants: 3,
  totalDuration: "40–60 seconds each",
  postingCadence: "Every 3 hours (11:00 / 14:00 / 17:00 WIB)",
  primaryHashtags: ["aniverse", "aianime", "animeart", "fyp"],
  ctaLink: "https://aniverse-one-khaki.vercel.app",
};
