/**
 * TikTok Short Video Script — July 24, 2026
 *
 * Generated by Agent A7 (Social Media Empire)
 * Format: 60-second time-lapse / showcase video
 * Style: Fast-paced, trending audio, visual focus
 *
 * Three video variants optimized for TikTok's algorithm:
 *   A) "8 Artworks in 60 Seconds" — fast showcase
 *   B) "From Prompt to Artwork" — AI generation process
 *   C) "Style Transformation Challenge" — same subject, different styles
 */

export interface TikTokScript {
  id: string;
  variant: "A" | "B" | "C";
  title: string;
  duration: number; // seconds
  audioSuggestion: string;
  scenes: TikTokScene[];
  caption: string;
  hashtags: string[];
  scheduledTime: string;
}

export interface TikTokScene {
  time: string; // timestamp e.g. "0:00"
  visual: string;
  textOverlay: string;
  voiceover: string;
  transition: string;
}

export const tiktokVariantA: TikTokScript = {
  id: "tt-a-20260724",
  variant: "A",
  title: "8 AI Anime Artworks in 60 Seconds 🔥",
  duration: 60,
  audioSuggestion: "Upbeat lo-fi / phonk remix — trending anime edit audio",
  scenes: [
    {
      time: "0:00",
      visual: "Neon Ronin full artwork — slow zoom in",
      textOverlay: "DAY 1 OF 8 AI ARTWORKS 🔥",
      voiceover: "Welcome to AniVerse — where AI meets anime art.",
      transition: "Zoom out + rotate",
    },
    {
      time: "0:07",
      visual: "The Spirit Tree's Embrace — pan up from roots to canopy",
      textOverlay: "GHIBLI INSPIRED 🌳",
      voiceover:
        "Today we generated 8 stunning pieces across trending styles.",
      transition: "Slide left",
    },
    {
      time: "0:14",
      visual: "Pixel Blade: Samurai Zero — pixel grid zoom effect",
      textOverlay: "16-BIT PIXEL ART 🎮",
      voiceover:
        "From retro 16-bit pixel art to Ghibli-inspired landscapes.",
      transition: "Flash transition",
    },
    {
      time: "0:21",
      visual: "Frieren's Evening — slow motion, petals falling",
      textOverlay: "FRIEREN VIBES 🌅",
      voiceover: "Dusty pastels are the BIGGEST trend right now.",
      transition: "Cross dissolve",
    },
    {
      time: "0:28",
      visual: "Sakura Station — cherry blossom close-up then wide shot",
      textOverlay: "WATERCOLOR DREAM 🌸",
      voiceover: "Watercolor textures give that nostalgic feel.",
      transition: "Wipe right",
    },
    {
      time: "0:35",
      visual: "Chronicles of the Verdant Gate — portal opening effect",
      textOverlay: "ISEKAI PORTAL 🚪",
      voiceover: "Isekai portal fantasy — always a fan favorite.",
      transition: "Zoom through portal",
    },
    {
      time: "0:42",
      visual: "Aurora Over Neo-Tokyo — sweeping city pan",
      textOverlay: "CYBERPUNK 🌃",
      voiceover: "Neon-lit cyberpunk with a natural aurora twist.",
      transition: "Fast upward scroll",
    },
    {
      time: "0:49",
      visual: "Lunar Festival Eve — sparkler light trails",
      textOverlay: "FESTIVAL MAGIC 🏮",
      voiceover:
        "Which one's your favorite? Comment below!",
      transition: "Slow fade",
    },
    {
      time: "0:55",
      visual: "AniVerse logo + app mockup on phone screen",
      textOverlay: "CREATE YOURS FREE → LINK IN BIO",
      voiceover: "Get 10 free generations at AniVerse. Link in bio!",
      transition: "Glitch effect to black",
    },
  ],
  caption:
    "8 AI anime artworks in 60 seconds 🔥 Which style is YOUR favorite? 1. Retro 90s Samurai 2. Ghibli Forest 3. Pixel Art 4. Frieren Pastel 5. Watercolor Station 6. Isekai Portal 7. Cyberpunk City 8. Festival Night\n\nCreate your own FREE at AniVerse 🎨 Link in bio!\n\n#animeart #aianime #aniverse #digitalart #animeedit #fyp #arttiktok",
  hashtags: [
    "animeart",
    "aianime",
    "aniverse",
    "digitalart",
    "animeedit",
    "fyp",
    "arttiktok",
    "animetok",
    "aiartwork",
    "animecommunity",
    "animefyp",
    "viralart",
    "artstyle",
    "animeshowcase",
    "aigenerated",
  ],
  scheduledTime: "2026-07-24T11:00:00+07:00",
};

export const tiktokVariantB: TikTokScript = {
  id: "tt-b-20260724",
  variant: "B",
  title: "From Prompt to Anime Artwork 🤯 | AI Generation Process",
  duration: 45,
  audioSuggestion:
    "Satisfying / ASMR typing sounds + magical reveal whoosh",
  scenes: [
    {
      time: "0:00",
      visual: "Typing prompt into AniVerse interface (close-up on text field)",
      textOverlay: "STEP 1: WRITE YOUR PROMPT 📝",
      voiceover:
        "Start with a vision. For this one, we wanted a cyberpunk samurai.",
      transition: "None",
    },
    {
      time: "0:08",
      visual: "Loading animation / progress bar on AniVerse",
      textOverlay: "STEP 2: AI GENERATES ⏳",
      voiceover: "Our AI model processes your prompt in seconds.",
      transition: "Fade through white",
    },
    {
      time: "0:18",
      visual: "Neon Ronin reveals — dramatic zoom out",
      textOverlay: "RESULT: NEON RONIN ⚡",
      voiceover: "And... boom. Neon Ronin in retro 90s cel-shaded glory.",
      transition: "Whoosh reveal",
    },
    {
      time: "0:28",
      visual: "Split screen: prompt text vs final artwork (3 examples)",
      textOverlay: "3 PROMPTS → 3 MASTERPIECES",
      voiceover:
        "From 'Ghibli forest with kodama' to 'Pixel art samurai' — AniVerse handles it all.",
      transition: "Grid split",
    },
    {
      time: "0:38",
      visual: "AniVerse app interface + CTA screen",
      textOverlay: "TRY IT FREE → ANIVERSE.APP",
      voiceover: "10 free generations waiting for you. Link in bio!",
      transition: "Zoom to CTA",
    },
  ],
  caption:
    "Watch AI turn words into anime art 🤯 From prompt to masterpiece in seconds. Try AniVerse FREE — link in bio! 🎨\n\n#aigenerated #animeart #prompttoart #satisfying #aniverse #creativeai #fyp",
  hashtags: [
    "aigenerated",
    "animeart",
    "prompttoart",
    "satisfying",
    "aniverse",
    "creativeai",
    "fyp",
    "aiartprocess",
    "artreveal",
    "aianime",
  ],
  scheduledTime: "2026-07-24T14:00:00+07:00",
};

export const tiktokVariantC: TikTokScript = {
  id: "tt-c-20260724",
  variant: "C",
  title: "Same Samurai, 4 Anime Styles 🔄 | AniVerse Challenge",
  duration: 35,
  audioSuggestion:
    "Fast beat switch / style change transition sound (trending)",
  scenes: [
    {
      time: "0:00",
      visual: "Question mark — silhouette of samurai",
      textOverlay: "SAME PROMPT... 4 STYLES? 🤔",
      voiceover:
        "What happens when you generate the same samurai in 4 different anime styles?",
      transition: "None",
    },
    {
      time: "0:05",
      visual: "Neon Ronin — cel-shaded retro style",
      textOverlay: "STYLE 1: RETRO 90s 🎬",
      voiceover: "Style one: Classic 90s OVA cel-shaded.",
      transition: "Swipe right",
    },
    {
      time: "0:12",
      visual: "Pixel Blade — pixel art version",
      textOverlay: "STYLE 2: PIXEL ART 🎮",
      voiceover: "Style two: 16-bit pixel art throwback.",
      transition: "Pixel dissolve",
    },
    {
      time: "0:19",
      visual: "Samurai in Ghibli-style soft landscape",
      textOverlay: "STYLE 3: GHIBLI 🌳",
      voiceover: "Style three: Ghibli-inspired warmth.",
      transition: "Cross dissolve",
    },
    {
      time: "0:26",
      visual: "Samurai in cyberpunk neon city",
      textOverlay: "STYLE 4: CYBERPUNK 🌃",
      voiceover: "And style four: full cyberpunk neon.",
      transition: "Glitch transition",
    },
    {
      time: "0:31",
      visual: "All 4 side by side → AniVerse logo",
      textOverlay: "WHICH STYLE WINS? 🏆",
      voiceover:
        "Which style wins? Try all of them FREE at AniVerse!",
      transition: "Split to single",
    },
  ],
  caption:
    "Same samurai, 4 completely different vibes 🔄 Which style wins? 1️⃣ Retro 90s 2️⃣ Pixel Art 3️⃣ Ghibli 4️⃣ Cyberpunk\n\nCreate your own style combos FREE at AniVerse 🎨 Link in bio!\n\n#styletransfer #animeart #aichallenge #samesubject #aniverse #aianime #fyp",
  hashtags: [
    "styletransfer",
    "animeart",
    "aichallenge",
    "samesubject",
    "aniverse",
    "aianime",
    "fyp",
    "artstyle",
    "animeedit",
    "comparison",
  ],
  scheduledTime: "2026-07-24T17:00:00+07:00",
};

export const tiktokMetadata = {
  date: "2026-07-24",
  variants: 3,
  totalDuration: "35–60 seconds each",
  postingCadence: "Every 3 hours (11:00 / 14:00 / 17:00 WIB)",
  primaryHashtags: ["aniverse", "aianime", "animeart", "fyp"],
  ctaLink: "https://aniverse-one-khaki.vercel.app",
};
