/**
 * Twitter/X Post Thread — July 26, 2026
 *
 * Generated by Agent A7 (Social Media Empire)
 * Features daily artwork from Agent A3 (Content Generation - Art)
 * Story tie-in: "Gerbang di Antara Dua Dunia" (Chapter 1) by A4
 *
 * Posting schedule (WIB):
 *   10:05 — Tweet 1 (Artwork showcase: Neon Ronin)
 *   10:15 — Tweet 2 (Story teaser: Gerbang di Antara Dua Dunia)
 *   10:25 — Tweet 3 (Style deep-dive: Retro '90s Anime)
 *   10:35 — Tweet 4 (Artist spotlight: CyberWeeb technique breakdown)
 *   10:45 — Tweet 5 (CTA to AniVerse with poll)
 */

export interface TwitterPost {
  id: string;
  tweetNumber: number;
  content: string;
  mediaAlt: string;
  scheduledTime: string;
  hashtags: string[];
}

export const twitterThread: TwitterPost[] = [
  {
    id: "tw-001",
    tweetNumber: 1,
    content:
      "🌀 Good morning, anime artists! Today's daily art drop is HERE. 🔥\n\nLead piece: \"Neon Ronin\" by CyberWeeb — a cel-shaded samurai standing defiant beneath rain-slicked neon streets. Retro '90s OVA energy meets Science SARU aesthetic.\n\n🎨 Style: Retro '90s Anime Revival\n🖌️ Artist: @CyberWeeb\n\nWhich artwork catches your eye first? 👇",
    mediaAlt:
      "Neon Ronin — A lone samurai in tattered crimson haori under magenta and cyan neon rain, cel-shaded 90s OVA style",
    scheduledTime: "2026-07-26T10:05:00+07:00",
    hashtags: ["AnimeArt", "AIArt", "NeonRonin", "AniVerse"],
  },
  {
    id: "tw-002",
    tweetNumber: 2,
    content:
      "📖 Storytime, AniVerse fam!\n\nOur latest web novel chapter \"Gerbang di Antara Dua Dunia\" (The Gate Between Two Worlds) just dropped! 🌟\n\nFollow Raka — a burned-out art student in Yogyakarta — who discovers his paintings are portals to a fantasy realm called Vallenwood. Armed with the Kuas Takdir (Brush of Destiny), he must defeat the Eternal Darkness.\n\nRead the full chapter on AniVerse → aniverse-one-khaki.vercel.app\n\nWhat would YOU paint if your brush could change reality? 🎨👇",
    mediaAlt:
      "Story teaser for AniVerse web novel: Gerbang di Antara Dua Dunia — fantasy isekai with a painter protagonist",
    scheduledTime: "2026-07-26T10:15:00+07:00",
    hashtags: ["WebNovel", "Isekai", "AniVerse", "FantasyWriting"],
  },
  {
    id: "tw-003",
    tweetNumber: 3,
    content:
      "🎬 RETRO '90s ANIME DEEP-DIVE 🎬\n\nThe cel-shaded revival is REAL and it's HERE to stay. Here's what makes it special:\n\n🔥 Thick, bold black outlines (think: OG Evangelion, Cowboy Bebop)\n🔥 High-saturation colors that POP\n🔥 Dramatic lens flares & cinematic framing\n🔥 Hand-painted background textures\n\n\"Neon Ronin\" by CyberWeeb nails ALL of these. The rain-slicked streets, the magenta fog, the cherry blossom petals — pure 1990s OVA magic.\n\nWant to create your own retro masterpiece? → aniverse-one-khaki.vercel.app",
    mediaAlt:
      "Style breakdown of Retro 90s Anime Revival aesthetic with examples from Neon Ronin artwork",
    scheduledTime: "2026-07-26T10:25:00+07:00",
    hashtags: ["RetroAnime", "90sAnime", "AnimeStyle", "ArtBreakdown"],
  },
  {
    id: "tw-004",
    tweetNumber: 4,
    content:
      "🖌️ SPOTLIGHT: CyberWeeb 🖌️\n\nThe artist behind today's lead piece \"Neon Ronin\" has been killing it with the retro cel-shaded aesthetic. Here's their secret sauce:\n\n⚡ Prompt structure: \"[subject] + [setting] + cel-shaded + thick black outlines + [era] OVA quality + cinematic composition\"\n⚡ Color philosophy: High contrast. Magenta+cyan against deep purple (#120458) creates that neon-noir feel.\n⚡ Texture trick: Add \"rain-slicked\" + \"steam rising from manhole\" for instant atmosphere.\n\nTry this prompt style on AniVerse → aniverse-one-khaki.vercel.app",
    mediaAlt:
      "CyberWeeb artist spotlight with prompt engineering tips for retro 90s anime style",
    scheduledTime: "2026-07-26T10:35:00+07:00",
    hashtags: ["CyberWeeb", "PromptEngineering", "AIArtTips", "AniVerse"],
  },
  {
    id: "tw-005",
    tweetNumber: 5,
    content:
      "🚀 Today's AniVerse art drop is a WRAP! 8 stunning pieces, 4 unique styles, and a brand new web novel chapter.\n\nWant to create YOUR own anime art or read the full story?\n\n✨ 10 FREE generations/month\n🎨 6+ style presets (Retro 90s, Ghibli, Cyberpunk, Pixel Art & more)\n📖 Original web novel chapters\n🖼️ Community gallery & marketplace\n\nStart creating FREE → aniverse-one-khaki.vercel.app\n\nWhich artwork is YOUR favorite? Vote below! 🗳️\n\n1️⃣ Neon Ronin\n2️⃣ Spirit Tree\n3️⃣ Pixel Blade\n4️⃣ Frieren's Evening\n5️⃣ Sakura Station\n6️⃣ Verdant Gate\n7️⃣ Aurora Neo-Tokyo\n8️⃣ Lunar Festival",
    mediaAlt:
      "AniVerse platform collage — 8 AI anime artworks in different styles with web novel promotion",
    scheduledTime: "2026-07-26T10:45:00+07:00",
    hashtags: [
      "AniVerse",
      "AIArt",
      "AnimeGeneration",
      "CreateWithAI",
      "DigitalArt",
    ],
  },
];

export const threadMetadata = {
  date: "2026-07-26",
  totalTweets: 5,
  primaryArtwork: "Neon Ronin",
  featuredArtists: ["CyberWeeb", "MoriArt", "PixelMage", "SakuraGen"],
  featuredStory: "Gerbang di Antara Dua Dunia — Chapter 1",
  platforms: ["Twitter/X"],
  postingWindow: "10:05–10:45 WIB",
  ctaLink: "https://aniverse-one-khaki.vercel.app",
};
