/**
 * Daily Artwork Descriptions — July 27, 2026
 *
 * Generated by Agent A3 (Content Generation - Art)
 * Based on Agent A1 market research report trending styles:
 *   - Ghibli-Inspired natural palettes (still dominant)
 *   - Cyberpunk Neons (evergreen "cool" aesthetic)
 *   - AI Caricature / Photo-to-Anime (viral trend)
 *   - Retro 90s Cel-Shaded (Science SARU influence)
 *   - High-Contrast Digital Painting (JJK/Demon Slayer style)
 *   - Vaporwave / Synthwave color trends
 */

export interface DailyArtwork {
  id: string;
  title: string;
  style: string;
  prompt: string;
  theme: string;
  genre: string;
  colorPalette: string[];
  artistAttribution: string;
  description: string;
  createdAt: string;
}

export const dailyArt: DailyArtwork[] = [
  {
    id: "art-001",
    title: "Ronin of the Neon Rain",
    style: "High-Contrast Digital Painting / Cyberpunk",
    prompt:
      "A stoic ronin with a battered katana standing in a neon-lit alleyway during heavy rain, cascading water dripping from his wide-brimmed straw hat, magenta and cyan neon signs reflecting off wet pavement, cel-shaded bold outlines with high contrast lighting, dynamic pose with hand resting on sword hilt, steam rising from manhole covers, dark moody atmosphere pierced by electric light, Jujutsu Kaisen-inspired dramatic framing with extreme shadows, 4K detailed rendering",
    theme: "High-Contrast / Ronin Cyberpunk",
    genre: "Action",
    colorPalette: ["#0A0A0A", "#FF006E", "#00F5FF", "#FFBE0B", "#3A0CA3"],
    artistAttribution: "CyberRonin",
    description:
      "A lone ronin stands motionless in a rain-lashed alley, neon signs casting electric magenta and cyan across his weathered straw hat and tattered haori. The composition channels modern action anime's signature high-contrast style — pools of absolute black punctuated by searing highlights on rain-wet surfaces. Every fold of his kimono, every scratch on his katana's tsuba is rendered with cel-shaded precision. Steam rises from heated ground as the neon city breathes around him.",
    createdAt: "2026-07-27T05:00:00Z",
  },
  {
    id: "art-002",
    title: "The Spirit Weaver's Grove",
    style: "Studio Ghibli-Inspired / Fantasy Landscape",
    prompt:
      "A hidden forest glade where giant luminescent mushrooms tower like cathedrals, their caps glowing in soft bioluminescent blues and warm ambers, a young girl with a staff woven from living vines sitting on a moss-covered stone, tiny will-o'-wisps dancing around her, a crystal-clear stream reflecting the ethereal light, Ghibli-inspired background with meticulous attention to foliage and water texture, Kodama spirits peeking from behind roots, warm earthy palette with magical glowing accents, peaceful wonder atmosphere",
    theme: "Ghibli-Inspired / Magical Forest",
    genre: "Fantasy",
    colorPalette: ["#2D4A22", "#6B8E4E", "#A8C686", "#4A90D9", "#E8C84A"],
    artistAttribution: "MoriArt",
    description:
      "Deep in an enchanted forest, cathedral-sized mushrooms cast their bioluminescent glow across a hidden glade. A young spirit weaver rests on a moss-covered stone, her staff entwined with living vines that pulse with soft light. Will-o'-wisps dance in lazy spirals around her as a crystal-clear stream mirrors the ethereal blues and ambers above. Every leaf, every patch of moss is rendered with Ghibli-level devotion to natural detail — the scene breathes with quiet magic and ancient peace.",
    createdAt: "2026-07-27T05:00:00Z",
  },
  {
    id: "art-003",
    title: "Photo-to-Anime: Street Style Portrait",
    style: "AI Caricature / Photo-to-Anime",
    prompt:
      "A hyper-stylized anime caricature of a street fashion model in Harajuku, exaggerated large expressive eyes with sparkle effects, oversized colorful outfit with layering, bright pink and turquoise hair styled in twin tails, thick expressive linework blending realism with chibi-inspired proportions, dynamic half-body portrait with urban Tokyo background blurred in bokeh, bubblegum and neon color scheme, playful and energetic mood, social-media-ready composition, trending caricature style with anime polish",
    theme: "Photo-to-Anime / Harajuku Fashion",
    genre: "Slice-of-Life",
    colorPalette: ["#FF69B4", "#00E5FF", "#FFE600", "#1A1A2E", "#FF8C42"],
    artistAttribution: "CaricatureAI",
    description:
      "A Harajuku street fashion icon transformed through the viral photo-to-anime lens — enormous expressive eyes catch the light with signature sparkle effects, twin tails in bubblegum pink and turquoise frame a face alive with personality. The caricature style amplifies every feature: oversized bow, layered statement pieces, confident half-smile. Thick, confident linework defines the figure while the Shibuya street background dissolves into dreamy bokeh. The piece captures the joy of self-expression through fashion, amplified by anime's most expressive conventions.",
    createdAt: "2026-07-27T05:00:00Z",
  },
  {
    id: "art-004",
    title: "Celestial Duel at Dusk",
    style: "Retro 90s Cel-Shaded / Action Anime",
    prompt:
      "Two warriors clashing mid-air above a traditional Japanese town at dusk, one wielding a crackling lightning blade, the other a swirling fire whip, thick cel-shaded outlines with no anti-aliasing, high saturation colors straight from the 1990s OVA palette, dramatic speed lines and impact frames, dynamic foreshortening, the setting sun casting long shadows, Science SARU-inspired fluid motion captured in a single freeze-frame, dust clouds and debris kicked up from the shockwave, vibrant reds and electric blues against warm amber sky",
    theme: "Retro 90s OVA / Cel-Shaded Battle",
    genre: "Action",
    colorPalette: ["#FF3300", "#0066FF", "#FFCC00", "#1A0033", "#FF9900"],
    artistAttribution: "RetroWave",
    description:
      "Freeze-framed at the moment of impact: two warriors suspended mid-air above a dusk-lit Japanese town, their weapons clashing in a burst of lightning and flame. The cel-shaded style is unapologetically retro — thick outlines, no anti-aliasing, colors ripped straight from a 1990s OVA palette. Speed lines radiate from the point of collision, debris frozen mid-explosion. The warm amber sky contrasts violently with electric blue and searing orange, capturing the raw energy of classic anime battle choreography with Science SARU's fluid sensibility.",
    createdAt: "2026-07-27T05:00:00Z",
  },
  {
    id: "art-005",
    title: "Neon Dreams: Vaporwave Station",
    style: "Cyberpunk / Vaporwave Synthwave",
    prompt:
      "An abandoned retro-futuristic train station frozen in time, checkered floor tiles stretching into infinite perspective, a lone figure in oversized 80s fashion standing before a wall of CRT monitors displaying glitched anime scenes, pink and cyan neon strips lining the vaulted ceiling, palm trees in decorative pots, a giant chrome statue of a classical bust in the center, digital grid floor reflections, purple sunset gradient sky visible through arched windows, nostalgic yet melancholic cyberpunk atmosphere, outrun aesthetic with anime soul",
    theme: "Vaporwave / Retro-Futurism",
    genre: "Sci-Fi",
    colorPalette: ["#FF00FF", "#00FFFF", "#1A0033", "#FF007F", "#7B2D8E"],
    artistAttribution: "NeonWeeb",
    description:
      "Time stands still in an abandoned vaporwave train station where the 1980s dream of the future meets digital decay. Checkered marble floors stretch toward infinity beneath a vaulted ceiling lined with pink and cyan neon strips. A lone figure in oversized retro fashion studies a wall of CRT monitors showing glitched anime scenes. Classical statues stand incongruously among potted palms, their chrome surfaces reflecting the purple-pink gradient of a digital sunset. The scene is pure outrun nostalgia — melancholy, beautiful, and drenched in neon.",
    createdAt: "2026-07-27T05:00:00Z",
  },
  {
    id: "art-006",
    title: "Paper Lantern Festival",
    style: "Watercolor & Soft Pastel / Festival Scene",
    prompt:
      "A riverside lantern festival at twilight, hundreds of floating paper lanterns drifting downstream reflecting warm golden and peach light on the water, a young couple in yukata watching from a wooden pier, willow trees framing the scene with drooping green branches, soft watercolor technique with visible paper texture, loose painterly brushwork, warm pastel palette of golds, peaches, and soft blues, distant firework sparkles in the fading sky, romantic and nostalgic atmosphere, Ghibli-inspired everyday magic in festival setting",
    theme: "Watercolor / Summer Festival Nostalgia",
    genre: "Slice-of-Life",
    colorPalette: ["#FFD700", "#FF9F68", "#FF6B6B", "#4A90D9", "#2E4A3A"],
    artistAttribution: "KiraKira",
    description:
      "Twilight settles over a riverside festival as hundreds of paper lanterns drift downstream, their warm golden glow reflecting off the water in shimmering streaks. A young couple in matching yukata watches from a weathered wooden pier, silhouetted against the soft light. Willow branches frame the scene, their drooping leaves catching the last blue of twilight. The watercolor technique gives everything a dreamy, nostalgic quality — loose edges where colors bleed into one another, visible paper grain, and a warm palette of golds, peaches, and powder blue.",
    createdAt: "2026-07-27T05:00:00Z",
  },
  {
    id: "art-007",
    title: "Aethel: The Chronomancer's Apprentice",
    style: "Digital Painting / Fantasy Character Design",
    prompt:
      "A young apprentice chronomancer with heterochromatic eyes (one gold, one silver), wearing an intricate coat stitched with clockwork patterns and constellation motifs, holding a pocket watch that trails golden ethereal threads into the air, her hair floating as if caught in a gentle time eddy, surrounded by floating hourglasses and clock faces at various angles, dramatic rim lighting from the magical glow of her time magic, high fantasy character design with meticulous costume detail, confident pose, modern digital painting with painterly textures",
    theme: "Fantasy Character / Time Magic",
    genre: "Fantasy",
    colorPalette: ["#0D1B2A", "#D4AF37", "#C0C0C0", "#1B3A4B", "#E8D5B7"],
    artistAttribution: "StarWeaver",
    description:
      "A young chronomancer stands at the nexus of past and future, her heterochromatic eyes — one gold, one silver — reflecting the weight of time itself. Her coat is a masterpiece of fantasy design: clockwork gears embroidered on the lapels, constellation patterns stitched in silver thread across the shoulders, golden epaulets catching the ethereal light. A pocket watch in her hand trails luminous golden threads that spiral into the air, connecting floating hourglasses and clock faces. Her hair drifts as if caught in a gentle time eddy, frozen mid-motion. The painterly digital style emphasizes rich textures — the gleam of metal, the softness of fabric, the glow of magic.",
    createdAt: "2026-07-27T05:00:00Z",
  },
  {
    id: "art-008",
    title: "Sakura Storm Over Cyber-Tokyo",
    style: "Cyberpunk / Bio-Luminescent Nature",
    prompt:
      "A dramatic fusion of nature and technology: a massive cybernetic cherry blossom tree growing through the ruins of a shattered skyscraper, its branches made of fiber-optic cables blooming with holographic pink petals, neon sap flowing like digital blood through translucent roots, the sky a gradient of toxic green to deep purple, bio-luminescent moss covering the crumbling concrete, a lone figure in a protective hazmat-style cloak gazing up at the bloom, post-cyberpunk aesthetic blending environmental collapse with haunting beauty, Blade Runner meets Princess Mononoke",
    theme: "Bio-Cyberpunk / Nature Reclaiming",
    genre: "Sci-Fi",
    colorPalette: ["#FF1493", "#39FF14", "#120458", "#00E5FF", "#FFD700"],
    artistAttribution: "MoriArt",
    description:
      "In a world where nature and technology have fused beyond recognition, a colossal cybernetic sakura tree erupts from the ruins of a shattered skyscraper. Its branches are fiber-optic cables, blooming not with petals but with holographic light-particles in cascading pink. Neon sap — vivid green and electric blue — pulses through translucent roots embedded in crumbling concrete. Bio-luminescent moss carpets every surface. A lone figure in a protective cloak stands beneath the impossible bloom, a witness to both destruction and rebirth. The piece channels the soul of cyberpunk while echoing Princess Mononoke's themes of nature's resilience.",
    createdAt: "2026-07-27T05:00:00Z",
  },
];
