/**
 * Daily Artwork Descriptions — July 28, 2026
 *
 * Generated by Agent A3 (Content Generation - Art)
 * Based on Agent A1 market research report trending styles:
 *   - Ghibli-Inspired natural palettes (still dominant)
 *   - High-Contrast Digital Painting / Cel-Shading (JJK/Demon Slayer)
 *   - Cyberpunk Neons (evergreen "cool" aesthetic)
 *   - Retro 90s Cel-Shaded (Science SARU influence)
 *   - Pastel Goth / Dusty Pastels (emerging trend)
 *   - Monochrome with Accent Color (popular for character art)
 *   - Bio-Luminescent Nature (Princess Mononoke × cyberpunk fusion)
 */

export interface DailyArtwork {
  id: string;
  title: string;
  style: string;
  prompt: string;
  theme: string;
  genre: string;
  colorPalette: string[];
  artistAttribution: string;
  description: string;
  imageUrl: string;
  createdAt: string;
}

export const dailyArt: DailyArtwork[] = [
  {
    id: "art-20260728-001",
    title: "The Sky Fisher's Last Catch",
    style: "Studio Ghibli-Inspired / Whimsical Fantasy",
    prompt:
      "An old fisherman in a floating boat anchored to a cloud, casting his line into a sea of stars above a sleeping village at dawn, his boat made of driftwood and held aloft by giant dandelion puffs, bioluminescent fish jumping through the starry void, warm golden sunrise painting the undersides of clouds, Ghibli-inspired pastoral magic with meticulous watercolor textures, soft earth tones with glowing highlights, kodama spirits watching from cloud edges, peaceful wonder and gentle melancholy atmosphere",
    theme: "Ghibli-Inspired / Celestial Fishing",
    genre: "Fantasy",
    colorPalette: ["#D4A76A", "#8B6F47", "#4A7C59", "#7EB8DA", "#F5E6C8"],
    artistAttribution: "GhibliDreamer",
    description:
      "High above a sleeping village, an old fisherman sits in a weathered boat held aloft by giant dandelion puffs. His line disappears into a sea of stars below, where bioluminescent fish arc through the void like living comets. The dawn sun paints the undersides of clouds in gradients of gold and peach, while tiny kodama spirits peek from cloud-edges. Every brushstroke carries Ghibli's reverence for nature's quiet magic — a scene suspended between dream and waking, where the sky yields its mysteries to those patient enough to wait.",
    imageUrl:
      "https://image.pollinations.ai/prompt/old_fisherman_float_boat_cloud_dandelion_puffs_star_sea_bi_fish_ghibli_warm_dawn_gentle_magic_watercolor?width=1024&height=1024&seed=42801&nologo=true",
    createdAt: "2026-07-28T05:00:00Z",
  },
  {
    id: "art-20260728-002",
    title: "Crimson Duel in the Bamboo Grove",
    style: "High-Contrast Digital Painting / Modern Action Anime",
    prompt:
      "Two duelists frozen mid-strike in a moonlit bamboo forest, one wielding a katana wreathed in crimson flames, the other a blade crackling with pale blue lightning, bamboo stalks exploding into splinters from the shockwave, dramatic high-contrast cel-shading with deep blacks and searing highlights, Jujutsu Kaisen-inspired dynamic foreshortening, extreme camera angle looking up from ground level, a single sakura petal caught in the shockwave, blood droplets suspended mid-air, thick confident linework with minimal anti-aliasing, violent beauty aesthetic",
    theme: "High-Contrast / Samurai Duel",
    genre: "Action",
    colorPalette: ["#000000", "#FF1A1A", "#00BFFF", "#8B0000", "#C0C0C0"],
    artistAttribution: "CelShadow",
    description:
      "The bamboo grove explodes into splinters as two blades meet in a shower of crimson fire and arctic lightning. The cel-shaded aesthetic pushes contrast to its limit — absolute black shadows against searing white highlights, with only the duelists' cursed energies providing color: one wreathed in blood-red flames, the other crackling with electric blue. The camera tilts up from ground level, magnifying the impact as bamboo stalks splinter mid-air and a single sakura petal hangs suspended in the shockwave. Every line is thick, confident, unapologetically bold.",
    imageUrl:
      "https://image.pollinations.ai/prompt/duel_bamboo_forest_moonlight_katana_fire_lightning_cel_shaded_high_contrast_JJK_style_dynamic_action?width=1024&height=1024&seed=42802&nologo=true",
    createdAt: "2026-07-28T05:00:00Z",
  },
  {
    id: "art-20260728-003",
    title: "Neon Shinobi, Third Shift",
    style: "Cyberpunk / Neon Noir",
    prompt:
      "A cyber-enhanced ninja crouched on a rain-slicked neon sign high above a megacity, her mechanical arm glowing with circuit traces that pulse magenta, a half-mask revealing one cybernetic eye with a cyan iris, holographic shurikens orbiting her wrist, reflections of neon advertisements in puddles three hundred meters below, steam vents from the city's underbelly creating atmospheric fog, blade-runner inspired cityscape with endless towering structures, magenta and cyan dominating the color palette with deep purple shadows, melancholic solitude of the urban hunter",
    theme: "Cyberpunk / Urban Ninja",
    genre: "Action / Sci-Fi",
    colorPalette: ["#FF006E", "#00F5FF", "#120458", "#1A0033", "#FFBE0B"],
    artistAttribution: "NeonShinobi",
    description:
      "High above the rain-lashed megacity, a cyber-enhanced shinobi perches on a flickering neon sign, her form silhouetted against a canvas of endless electric towers. Her mechanical arm pulses with magenta circuit traces, and holographic shurikens orbit her wrist in lazy arcs. Rain streams down her half-mask as her cybernetic eye — a brilliant cyan iris — scans the city below. The scene channels the eternal solitude of the urban hunter: wrapped in steam and neon, a ghost in the machine of a city that never sleeps.",
    imageUrl:
      "https://image.pollinations.ai/prompt/cyber_ninja_crouching_neon_sign_rain_megacity_mechanical_arm_magenta_cyan_blade_runner_atmosphere?width=1024&height=1024&seed=42803&nologo=true",
    createdAt: "2026-07-28T05:00:00Z",
  },
  {
    id: "art-20260728-004",
    title: "Galactic Battle High: After School",
    style: "Retro 90s Cel-Shaded / Sci-Fi School Anime",
    prompt:
      "Three students in a modified Japanese high school uniform standing back-to-back on the roof of their school, which is actually a starship hovering above a nebula, one holding a transforming staff, one with mechanical wings unfolding, one charging a spiral energy attack in her palm, thick cel-shaded outlines with no anti-aliasing, high-saturation 1990s OVA colors, dramatic speed lines radiating from their poses, the nebula swirling in pinks and purples below, Science SARU-inspired fluidity frozen in a single impact frame, retro anime aesthetic with modern polish",
    theme: "Retro 90s OVA / Magical School Sci-Fi",
    genre: "Sci-Fi / Action",
    colorPalette: ["#FF6600", "#00CCFF", "#FF00FF", "#FFFF00", "#330066"],
    artistAttribution: "RetroWave",
    description:
      "The school bell rings — except this school is a starship hovering above a swirling nebula. Three students stand back-to-back on the roof, their modified sailor uniforms billowing in the cosmic wind. One grips a transforming staff that hums with energy, another unfurls mechanical wings that catch the nebula's pink light, and the third charges a spiral of pure energy in her palm. The cel-shaded style is pure 1990s OVA: thick outlines, eye-searing saturation, speed lines radiating from every limb. Science SARU energy frozen in a single frame of pure, unapologetic anime cool.",
    imageUrl:
      "https://image.pollinations.ai/prompt/three_school_students_back_to_back_starship_roof_nebula_90s_OVA_cel_shaded_vibrant_retro_anime?width=1024&height=1024&seed=42804&nologo=true",
    createdAt: "2026-07-28T05:00:00Z",
  },
  {
    id: "art-20260728-005",
    title: "The Witch's Dusty Garden",
    style: "Pastel Goth / Dusty Pastels",
    prompt:
      "A young witch with silver hair and a tattered hat tending a moonlit garden of black roses and luminescent fungi, her dress a dusty lavender with dark lace trim, a crow with one white eye perched on her staff, gothic iron gate overgrown with pale pink climbing roses, soft desaturated pastel colors with sharp dark accents, muted purples and dusty pinks against charcoal blacks, firefly-like spores drifting through the air, melancholic beauty with a gentle warmth, Pinterest-aesthetic pastel goth, soft glowing highlights on the fungi caps",
    theme: "Pastel Goth / Witchy Garden",
    genre: "Fantasy",
    colorPalette: ["#C9A0DC", "#E8C4D4", "#2D1B36", "#8B6F8A", "#D4AFB9"],
    artistAttribution: "MoonThistle",
    description:
      "In a moonlit garden where black roses bloom beside luminescent fungi, a silver-haired witch tends her midnight harvest. Her tattered hat casts shadows over gentle features, and her dusty lavender dress — trimmed in dark lace — rustles as she moves. A crow with one white eye guards from atop her gnarled staff. The color palette is all dusty pastels and soft shadows: muted lavender, faded pink, charcoal gray against the bioluminescent glow of the fungi. It is melancholy but not sad — the quiet beauty of a garden that thrives in twilight, where even darkness wears soft colors.",
    imageUrl:
      "https://image.pollinations.ai/prompt/pastel_goth_witch_moonlit_garden_black_roses_bi_fungi_silver_hair_dusty_lavender_melancholy_beauty?width=1024&height=1024&seed=42805&nologo=true",
    createdAt: "2026-07-28T05:00:00Z",
  },
  {
    id: "art-20260728-006",
    title: "The Red String of Fate",
    style: "Monochrome with Accent Color / Character Portrait",
    prompt:
      "A striking character portrait in predominantly monochrome greyscale, a young man with flowing white hair and traditional Japanese attire, the only color being a vivid crimson thread tied around his little finger that trails away into the misty background, dramatic rim lighting illuminating his sharp features from one side, his expression carrying quiet determination, subtle grey gradients creating depth in the fabric of his kimono, the red string glowing faintly and drawing the eye as the sole color element, minimalist composition emphasizing the power of a single accent",
    theme: "Monochrome with Red Accent / Fate & Destiny",
    genre: "Fantasy",
    colorPalette: ["#FFFFFF", "#EAEAEA", "#666666", "#1A1A1A", "#FF1A1A"],
    artistAttribution: "MonoAccent",
    description:
      "In a world rendered entirely in shades of grey, a single thread of fate burns crimson. A young man with flowing white hair and traditional Japanese attire stands against a misty void, his features carved by dramatic rim lighting from one side. Every fold of his kimono, every strand of hair is rendered in meticulous greyscale — from pure white highlights to absolute black shadows. But from his raised hand trails a vivid red thread, the sole point of color in the composition, glowing faintly as it disappears into the unknown. The minimalism makes the accent explosive: love, destiny, or doom — the thread carries all possibilities.",
    imageUrl:
      "https://image.pollinations.ai/prompt/monochrome_portrait_white_hair_man_kimono_red_thread_fate_accent_color_dramatic_rim_lighting?width=1024&height=1024&seed=42806&nologo=true",
    createdAt: "2026-07-28T05:00:00Z",
  },
  {
    id: "art-20260728-007",
    title: "The Abyss Blooms With Light",
    style: "Bio-Luminescent Nature / Post-Cyberpunk",
    prompt:
      "A vast underground cavern where colossal crystal formations pulse with bio-luminescent light in deep blues, teals, and violets, a river of liquid crystal winding through the cavern floor, strange flora that are half-plant half-technology growing along the banks, a hooded figure standing on a natural stone bridge gazing into the glowing depths, their cloak embroidered with fiber-optic thread, giant moth-like creatures with translucent wings drifting through the air, bioluminescent spores floating like snow, Princess Mononoke meets Avatar's Pandora with a cybernetic soul, breathtaking scale and wonder",
    theme: "Bio-Luminescent / Subterranean Wonder",
    genre: "Fantasy / Sci-Fi",
    colorPalette: ["#0A1A2B", "#00B4D8", "#7209B7", "#00F5D4", "#0077B6"],
    artistAttribution: "DeepBloom",
    description:
      "Deep beneath the earth, a cathedral of crystal pulses with ancient light. Massive formations of amethyst and sapphire rise from the cavern floor, their inner glow casting the vast space in deep blues and violets. A river of liquid crystal winds through the chamber, reflecting the bioluminescent flora that line its banks — plants that are half-organic, half-mechanical, their leaves tracing circuits of soft light. Giant moth-creatures with translucent wings drift through the air as luminous spores fall like snow. On a natural stone bridge, a hooded figure gazes into the radiant abyss — a witness to the sublime marriage of nature and technology, deep earth and electric dream.",
    imageUrl:
      "https://image.pollinations.ai/prompt/underground_cavern_bi_crystal_flora_technology_fusion_hooded_figure_bridge_giant_moths_ethereal?width=1024&height=1024&seed=42807&nologo=true",
    createdAt: "2026-07-28T05:00:00Z",
  },
];
