/**
 * Daily Artwork Descriptions — July 24, 2026
 *
 * Generated by Agent A3 (Content Generation - Art)
 * Based on Agent A1 market research report trending styles:
 *   - Retro '90s Anime Revival (Science SARU)
 *   - Studio Ghibli-Inspired
 *   - Pixel Art + Anime Fusion
 *   - Cyberpunk & Neon
 *   - Watercolor & Soft Pastels
 *   - Dusty Pastels / Frieren-style
 *   - Warm Earth Tones
 */

export interface DailyArtwork {
  id: string;
  title: string;
  style: string;
  prompt: string;
  theme: string;
  genre: string;
  colorPalette: string[];
  artistAttribution: string;
  description: string;
  createdAt: string;
}

export const dailyArt: DailyArtwork[] = [
  {
    id: "art-001",
    title: "Neon Ronin",
    style: "Retro '90s Anime",
    prompt:
    "A lone samurai standing on a rain-slicked neon street, cherry blossom petals drifting through magenta fog, cel-shaded with thick black outlines, vibrant high-saturation colors, Science SARU aesthetic, dramatic lens flare from a flickering street lamp, 1990s OVA quality, cinematic composition",
    theme: "Retro '90s Anime Revival / Cyberpunk Fusion",
    genre: "Action",
    colorPalette: ["#FF1493", "#00FFFF", "#120458", "#FFD700", "#FF4500"],
    artistAttribution: "CyberWeeb",
    description:
    "A ronin in a tattered crimson haori stands beneath a flickering neon sign. Rain streaks through beams of magenta and cyan light. Cherry blossom petals, rendered in thick cel-shaded strokes, spiral through the steam rising from a manhole cover. The piece channels the gritty, vibrant aesthetic of 1990s OVAs with Science SARU's dynamic framing.",
    createdAt: "2026-07-24T05:00:00Z",
  },
  {
    id: "art-002",
    title: "The Spirit Tree's Embrace",
    style: "Studio Ghibli-Inspired",
    prompt:
    "A massive ancient tree with glowing blue leaves towering over a rolling green hillside, warm golden sunlight streaming through branches, a small stone shrine at the base, fluffy white clouds in a soft blue sky, Ghibli background art style, detailed foliage, warm earth tones, whimsical and peaceful atmosphere, Kodama spirits peeking from behind roots",
    theme: "Ghibli-Inspired Fantasy Landscape",
    genre: "Fantasy",
    colorPalette: ["#7CB342", "#5D4037", "#FFD54F", "#81D4FA", "#A5D6A7"],
    artistAttribution: "MoriArt",
    description:
    "A colossal ancient tree with luminescent azure leaves dominates a pastoral landscape. Warm golden-hour light filters through its canopy, casting dappled shadows on emerald grass. Tiny Kodama spirits peek from behind gnarled roots. The composition mirrors Studio Ghibli's mastery of background art — detailed, lush, and deeply atmospheric.",
    createdAt: "2026-07-24T05:00:00Z",
  },
  {
    id: "art-003",
    title: "Pixel Blade: Samurai Zero",
    style: "Pixel Art + Anime Fusion",
    prompt:
    "16-bit pixel art style anime character, a samurai with glowing neon sword, dynamic action pose against a starry night sky, pixelated slash trails in electric blue, retro RPG aesthetic meets modern anime design, 2.5D layered depth, limited palette with dithering effects, parallax background of a feudal Japan town with neon accents",
    theme: "Pixel Art / Retro Gaming Anime",
    genre: "Action",
    colorPalette: ["#212529", "#4361EE", "#F72585", "#7209B7", "#4CC9F0"],
    artistAttribution: "PixelMage",
    description:
    "A samurai warrior rendered in detailed 16-bit pixel art, poised mid-strike with a katana wreathed in electric blue energy. The background layers a feudal Japanese village with subtle neon accents — a fusion of retro RPG aesthetics and modern anime character design. Dithering and limited palette techniques give it an authentic retro gaming feel.",
    createdAt: "2026-07-24T05:00:00Z",
  },
  {
    id: "art-004",
    title: "Frieren's Evening",
    style: "Dusty Pastel / Frieren-Inspired",
    prompt:
    "A lone mage with flowing white hair and a wide-brimmed hat walking through a field of wildflowers at sunset, soft muted pastel colors, dusty warm palette, melancholy atmosphere, gentle breeze rustling her cloak, distant mountains fading into warm haze, Frieren-inspired aesthetic, watercolor-like texture, emotional storytelling through composition",
    theme: "Dusty Pastels / Fantasy Romance",
    genre: "Fantasy",
    colorPalette: ["#E8D5B7", "#C9A88D", "#9B7B6E", "#F4E4C1", "#B8A99A"],
    artistAttribution: "SakuraGen",
    description:
    "A solitary mage with flowing white hair walks through an endless field of wildflowers as the sun sets in dusty rose and amber. Her robes trail behind her, catching the warm breeze. The palette is deliberately muted and warm — dusty pastels that evoke the melancholy beauty of Frieren's world. Soft, painterly textures give the scene a watercolor quality.",
    createdAt: "2026-07-24T05:00:00Z",
  },
  {
    id: "art-005",
    title: "Sakura Station",
    style: "Watercolor & Soft Pastel",
    prompt:
    "A quiet train station platform in spring, cherry blossom trees in full bloom on both sides, petals falling gently, a lone figure waiting under the station clock, soft watercolor technique, pastel pink and lavender sky, gentle morning light, romantic slice-of-life atmosphere, loose brushwork, paper texture visible, Ghibli-inspired everyday magic",
    theme: "Watercolor / Slice-of-Life Romance",
    genre: "Slice-of-Life",
    colorPalette: ["#FFB7C5", "#D4A5B6", "#C5D5E0", "#F7E7CE", "#A8C4D8"],
    artistAttribution: "KiraKira",
    description:
    "A quiet morning at a rural train station during peak cherry blossom season. Pink petals drift across the platform as a lone figure waits beneath the station clock. The soft watercolor technique gives the scene a dreamy, nostalgic quality — loose edges where colors bleed into one another, visible paper grain, and a pastel palette of blush pinks, lavender, and powder blue.",
    createdAt: "2026-07-24T05:00:00Z",
  },
  {
    id: "art-006",
    title: "Chronicles of the Verdant Gate",
    style: "Warm Earth Tones / Isekai Fantasy",
    prompt:
    "A magical portal of intertwined vines and glowing runes opening in an ancient forest, a modern-day teenager in uniform stepping through, the other side revealing a floating continent in the sky, warm earth tones with emerald green accents, detailed fantasy architecture of floating ruins, party members waiting on the other side, isekai genre, vibrant yet natural palette",
    theme: "Warm Earth Tones / Isekai Adventure",
    genre: "Isekai",
    colorPalette: ["#2E5C3E", "#8B6F47", "#D4A574", "#5B7B5E", "#C4A77D"],
    artistAttribution: "DawnArtist",
    description:
    "In an ancient forest dappled with golden light, a teenager in a school uniform reaches toward a shimmering portal woven from vines and glowing runes. Beyond the gate, a floating continent hangs against a warm amber sky — complete with floating ruins and fantastical architecture. Rich earth tones ground the scene while emerald and amber accents guide the eye through the composition.",
    createdAt: "2026-07-24T05:00:00Z",
  },
  {
    id: "art-007",
    title: "Aurora Over Neo-Tokyo",
    style: "Cyberpunk & Neon",
    prompt:
    "A sprawling futuristic megacity at night seen from above, aurora borealis in green and purple sweeping across the sky, holographic billboards in Japanese characters, flying vehicles with light trails, neon-lit skyscrapers towering into the clouds, cyberpunk aesthetic with a natural aurora twist, dramatic scale, electric cyan and magenta highlights, rain-slicked surfaces reflecting city lights",
    theme: "Cyberpunk / Sci-Fi Cityscape",
    genre: "Sci-Fi",
    colorPalette: ["#0A0A23", "#00F5FF", "#FF00FF", "#39FF14", "#7B2D8E"],
    artistAttribution: "NeonWeeb",
    description:
    "A breathtaking aerial view of a cyberpunk megacity at midnight. Skyscrapers pierce the clouds, their surfaces alive with holographic advertisements in kanji and neon script. Above it all, a natural aurora borealis swirls in electric green and violet — a juxtaposition of nature and technology. Flying vehicles trace light paths between buildings. Rain-slicked rooftops mirror the neon chaos below.",
    createdAt: "2026-07-24T05:00:00Z",
  },
  {
    id: "art-008",
    title: "Lunar Festival Eve",
    style: "Warm Earth Tones / Ghibli Character",
    prompt:
    "Two children in traditional yukata running through a nighttime festival, paper lanterns in warm amber and red lighting the street, a massive paper moon hanging in the background, food stalls with steam rising, sparklers in their hands leaving light trails, Ghibli character style, warm firelight tones against deep indigo night, sense of wonder and childhood adventure",
    theme: "Ghibli-Inspired / Slice-of-Life Festival",
    genre: "Slice-of-Life",
    colorPalette: ["#1A1A2E", "#E8A838", "#D4563E", "#F5D6A8", "#4A3F5C"],
    artistAttribution: "EmberForge",
    description:
    "Two children dash through a lantern-lit festival street, their yukata fluttering behind them. Paper lanterns in shades of amber, crimson, and gold cast a warm glow against the deep indigo night. A giant illuminated paper moon floats above the crowd. Sparklers in their hands paint trails of light through the air. The scene captures a Ghibli-esque sense of childhood wonder and summer magic.",
    createdAt: "2026-07-24T05:00:00Z",
  },
];
