/**
 * Daily Artwork Descriptions — July 25, 2026
 *
 * Generated by Agent A3 (Content Generation - Art)
 * Based on Agent A1 market research report (2026-07-25) trending styles:
 *   - '90s Retro Anime Boom (VHS Grain / Science SARU)
 *   - Vaporwave Anime Revival (TikTok #vaporwaveanime)
 *   - Frieren-Effect / Dusty Pastels (Most Dominant Palette)
 *   - Art Nouveau x Anime Fusion (Niche Growing)
 *   - Sepia Nostalgia (TikTok #animeedit)
 *   - Pastel Goth (Emerging Alternative)
 *   - Warm Earth + Emerald (Ghibli-Inspired Evergreen)
 */

export interface DailyArtwork {
  id: string;
  title: string;
  style: string;
  prompt: string;
  theme: string;
  genre: string;
  colorPalette: string[];
  artistAttribution: string;
  description: string;
  createdAt: string;
}

export const dailyArt: DailyArtwork[] = [
  {
    id: "art-001",
    title: "VHS Memories",
    style: "'90s Retro Anime (VHS Grain)",
    prompt:
      "A teenage girl in a oversized denim jacket listening to a Walkman on a Tokyo rooftop at sunset, heavy cel-shading with thick black outlines, VHS scan lines overlay effect, chromatic aberration at edges, high-saturation neon colors bleeding into each other, Science SARU dynamic perspective, 1990s OVA aesthetic, grainy film texture, nostalgic warm glow, Japanese cityscape with retro billboards in background",
    theme: "'90s Retro Anime Revival / VHS Nostalgia",
    genre: "Slice-of-Life",
    colorPalette: ["#FF6B35", "#0047AB", "#E31837", "#FFD700", "#1A1A2E"],
    artistAttribution: "RetroWavePunk",
    description:
      "A girl in an oversized denim jacket stands on a rain-washed Tokyo rooftop, white earbuds trailing from a vintage Walkman clipped to her waist. The scene pulses with exaggerated cel-shaded colors — deep cobalt sky, blazing orange sunset, crimson highlights catching every edge. VHS grain overlays the image while chromatic aberration at the frame edges sells the retro CRT monitor feel. The composition channels Science SARU's signature dynamic angles and bold, unapologetic color contrasts.",
    createdAt: "2026-07-25T05:00:00Z",
  },
  {
    id: "art-002",
    title: "Futur Funk Dreamscape",
    style: "Vaporwave / Future Funk",
    prompt:
      "A Greek bust rendered in pink neon floating above a grid-lined digital ocean at sunset, a lone anime girl with 90s aesthetic standing on a pier silhouetted against a gradient sky of magenta, cyan, and orange, retro Windows 95 UI elements floating in the foreground, palm trees silhouettes, VHS static at edges, synthwave sun with horizontal scan lines, nostalgic 80s/90s digital aesthetic, dreamy vaporwave atmosphere, high contrast with pastel neon accents",
    theme: "Vaporwave Anime Revival / Future Funk",
    genre: "Sci-Fi",
    colorPalette: ["#FF6B9D", "#00D4FF", "#FFD700", "#6C0CE8", "#FF2E63"],
    artistAttribution: "NeonDreamer",
    description:
      "A surreal digital dreamscape where a Greek marble bust rendered in glowing neon pink floats above an infinite grid extending toward a synthwave horizon. On a pier jutting into the pixelated ocean, an anime girl in '90s streetwear stands silhouetted against a gradient sky of electric magenta, cyan, and gold. Windows 95 error messages and floating UI panels drift in the foreground like digital confetti. The piece perfectly captures the TikTok-viral vaporwave anime aesthetic — nostalgic, surreal, and drenched in retro digital texture.",
    createdAt: "2026-07-25T05:00:00Z",
  },
  {
    id: "art-003",
    title: "The Last Campfire",
    style: "Dusty Pastel / Frieren-Inspired",
    prompt:
      "A party of four adventurers resting around a campfire under a star-dusted twilight sky, a white-haired elven mage in a wide-brimmed hat warming her hands, soft dusty pastel color palette of muted rose, warm beige, sage green, and faded lavender, Frieren-inspired melancholy atmosphere, gentle warm firelight illuminating their faces, distant mountains silhouetted in hazy twilight, wildflowers swaying in a gentle breeze, painterly watercolor texture, sense of quiet companionship and lingering sadness",
    theme: "Frieren-Effect / Fantasy Journey",
    genre: "Fantasy",
    colorPalette: ["#D4A5B6", "#E8D5B7", "#9BAA8D", "#B8A9C9", "#C9A88D"],
    artistAttribution: "EternalTraveler",
    description:
      "Four weary travelers gather around a crackling campfire beneath a vast star-dusted sky. At the center, a white-haired elven mage in a familiar wide-brimmed hat gazes into the flames, her expression peaceful yet touched with melancholy. Warm firelight casts gentle shadows across their faces, while the world beyond fades into soft hazy twilight. The palette is deliberately muted — dusty rose, warm beige, sage green, and faded lavender blending like watercolors on textured paper. The scene channels Frieren's quiet meditation on time, memory, and the bittersweet beauty of long journeys shared with those who will eventually depart.",
    createdAt: "2026-07-25T05:00:00Z",
  },
  {
    id: "art-004",
    title: "Mucha's Celestial Maiden",
    style: "Art Nouveau x Anime Fusion",
    prompt:
      "An anime-style maiden with flowing emerald hair intertwined with flowering vines, ornate Art Nouveau decorative borders inspired by Alphonse Mucha, stained glass panel background in jewel tones, halo of golden geometric patterns behind her head, intricate botanical motifs framing the composition, elegant flowing lines and curves, peacock feathers and flowering lotus details, ethereal expression, warm gold, teal, and ruby color palette, decorative typography space at bottom, premium art print aesthetic",
    theme: "Art Nouveau x Anime Crossover",
    genre: "Fantasy",
    colorPalette: ["#D4AF37", "#1B6B5B", "#8B1A1A", "#2A0845", "#C4845A"],
    artistAttribution: "BelleEpoqueArt",
    description:
      "An ethereal anime maiden with cascading emerald hair woven with flowering vines gazes serenely from within an ornate Art Nouveau frame. Her hair flows into decorative swirls that echo Alphonse Mucha's iconic style, merging with botanical motifs of lotus flowers and peacock feathers. Behind her, a stained-glass halo in jewel tones — ruby, gold, and teal — radiates geometric patterns. The composition is wrapped in elaborate decorative borders with stylized typography space below. The fusion of Mucha's Belle Époque elegance with modern anime character design creates a uniquely luxurious aesthetic, perfectly suited for premium gallery prints.",
    createdAt: "2026-07-25T05:00:00Z",
  },
  {
    id: "art-005",
    title: "Grandmother's Photo Album",
    style: "Sepia Nostalgia",
    prompt:
      "A vintage photograph-style anime scene of a young couple sitting on a wooden bench in a 1970s Japanese park, sepia-toned with faded warm browns and cream highlights, film grain texture, light leaks and dust spots, slightly faded edges, decorative border like an old photo print, the girl in a traditional shifuku smiling shyly at the boy in a retro school uniform, cherry blossoms raining softly, nostalgic bittersweet atmosphere, analog warmth, hand-written date in corner: Showa 48",
    theme: "Sepia Nostalgia / Retro Romance",
    genre: "Romance",
    colorPalette: ["#8B7355", "#D4B896", "#A0805A", "#4A3728", "#E8D5B0"],
    artistAttribution: "VintageFrame",
    description:
      "A faded sepia-toned photograph captures a young couple on a park bench in 1970s Japan. The boy in a dark retro school uniform leans forward, laughing, while the girl in a traditional shifuku covers her smile with her hand, her eyes crinkling with shy affection. Cherry blossom petals scatter across the scene like confetti frozen in time. Film grain textures, subtle light leaks, and soft edge fading give the image the authentic feel of a decades-old photo print found in a grandmother's album. The hand-written date 'Showa 48.4.15' in the corner grounds it in a specific, tender moment of youth and first love.",
    createdAt: "2026-07-25T05:00:00Z",
  },
  {
    id: "art-006",
    title: "Witch of the Violet Hour",
    style: "Pastel Goth",
    prompt:
      "A young witch with short charcoal-black hair and purple highlights wearing a oversized knit sweater and pleated skirt, sitting on a wrought-iron balcony overlooking a foggy city at twilight, muted purple and charcoal color palette with dusty pink accents, soft goth aesthetic, a black cat curled in her lap, glowing violet magical symbols floating around her fingers, melancholic yet cozy atmosphere, muted teal distant city lights, alternative fashion details — silver rings, choker necklace, worn combat boots, painterly soft shading",
    theme: "Pastel Goth / Cozy Occult",
    genre: "Slice-of-Life",
    colorPalette: ["#7B5EA7", "#36454F", "#D4A5B6", "#5E9B9B", "#2D1B3D"],
    artistAttribution: "MoonlitMuse",
    description:
      "On a wrought-iron balcony high above a fog-veiled city at twilight, a young witch with charcoal-black hair tipped in violet absently traces glowing arcane symbols in the air. She's bundled in an oversized charcoal knit sweater, pleated skirt, and worn combat boots — the uniform of the modern alternative witch. A black cat dozes in her lap as distant teal lights flicker through the mist below. The palette is a study in soft darkness — muted purple, charcoal gray, dusty pink, and muted teal blending into a dreamy, cozy melancholia. Pastel goth meets urban fantasy in this intimate portrait of quiet magical solitude.",
    createdAt: "2026-07-25T05:00:00Z",
  },
  {
    id: "art-007",
    title: "Guardian of the Ancient Wood",
    style: "Warm Earth + Emerald (Ghibli-Inspired)",
    prompt:
      "A massive forest spirit in the form of a wolf made of glowing emerald moss and blooming flowers standing guard before an ancient shrine deep in a primeval forest, golden sunlight streaming through towering cedar trees, glowing firefly-like wisps of light floating in the air, rich warm earth tones of deep brown and gold contrasted with vibrant emerald green, detailed moss-covered stone lanterns, roots intertwined with Torii gate, Ghibli-style background art sense of scale and wonder, Kodama spirits watching from tree hollows",
    theme: "Ghibli-Inspired / Forest Spirit Fantasy",
    genre: "Fantasy",
    colorPalette: ["#2E5C3E", "#8B6F47", "#D4A574", "#4A7C4F", "#C4A77D"],
    artistAttribution: "ForestWhisper",
    description:
      "Deep in a primeval forest where sunlight streams through towering cedars in golden shafts, a colossal wolf-spirit made of living moss, emerald foliage, and blooming wildflowers stands guard before an ancient shrine. Its body is intertwined with glowing roots and petals — a living embodiment of the forest itself. Stone lanterns encrusted with moss line the path, and a weathered Torii gate is nearly consumed by climbing vines and roots. Tiny Kodama spirits peek from tree hollows while firefly-like wisps drift through the golden air. The scene captures Studio Ghibli's unmatched ability to convey both the majesty and intimate detail of nature, rendered in rich warm earth tones and vibrant emerald greens.",
    createdAt: "2026-07-25T05:00:00Z",
  },
];
